
/* ############################################################# */
/* ### Copyright © 2026 Maxim Rysevets. All rights reserved. ### */
/* ############################################################# */

import Foundation

extension Date {

    enum Format: String {
        case iso8601         = "yyyy-MM-dd HH:mm:ss"
        case iso8601Timezone = "yyyy-MM-dd HH:mm:ss Z"
        case iso8601Mono     = "yyyyMMdd_HHmmss"
        case convenientDate  = "d MMM yyyy"
        case convenientTime  = "HH:mm:ss"
    }

    var formatConvenient: String {
        let formatter = DateFormatter()
        formatter.dateFormat = String(
            format: NSLocalizedString("%@ 'at' %@", comment: ""),
            Self.Format.convenientDate.rawValue,
            Self.Format.convenientTime.rawValue )
        return formatter.string(from: self)
    }

    var formatISO8601withTZ: String {
        let formatter = DateFormatter()
        formatter.dateFormat = Self.Format.iso8601Timezone.rawValue
        formatter.locale = Locale(identifier: "en_US_POSIX")
        return formatter.string(from: self)
    }

    var formatISO8601: String {
        let formatter = DateFormatter()
        formatter.dateFormat = Self.Format.iso8601Timezone.rawValue
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.timeZone = TimeZone(secondsFromGMT: 0)
        return formatter.string(from: self)
    }

    var formatISO8601Mono: String {
        let formatter = DateFormatter()
        formatter.dateFormat = Self.Format.iso8601Mono.rawValue
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.timeZone = TimeZone(secondsFromGMT: 0)
        let mSec = Int(Self().timeIntervalSince1970.fractionalPart * 1_000)
        return formatter.string(from: self) + "-\(mSec)"
    }

    var day   : Int { get { Calendar.current.component(.day   , from: self) } set { self._updateComponent(day   : newValue) } }
    var month : Int { get { Calendar.current.component(.month , from: self) } set { self._updateComponent(month : newValue) } }
    var year  : Int { get { Calendar.current.component(.year  , from: self) } set { self._updateComponent(year  : newValue) } }
    var hour  : Int { get { Calendar.current.component(.hour  , from: self) } set { self._updateComponent(hour  : newValue) } }
    var minute: Int { get { Calendar.current.component(.minute, from: self) } set { self._updateComponent(minute: newValue) } }
    var second: Int { get { Calendar.current.component(.second, from: self) } set { self._updateComponent(second: newValue) } }

    private mutating func _updateComponent(
        day   : Int? = nil,
        month : Int? = nil,
        year  : Int? = nil,
        hour  : Int? = nil,
        minute: Int? = nil,
        second: Int? = nil,
    ) {
        var components = Calendar.current.dateComponents([
            .day, .month, .year, .hour, .minute, .second
        ], from: self)

        if let day    { components.day    = day }
        if let month  { components.month  = month }
        if let year   { components.year   = year }
        if let hour   { components.hour   = hour }
        if let minute { components.minute = minute }
        if let second { components.second = second }

        if let newDate = Calendar.current.date(from: components) {
            self = newDate
        }
    }

    static public let MONTH_NAMES = [
         1: "January",
         2: "February",
         3: "March",
         4: "April",
         5: "May",
         6: "June",
         7: "July",
         8: "August",
         9: "September",
        10: "October",
        11: "November",
        12: "December",
    ]

    static public let TIME_ZONES: [(offset: String, name: String)] = [
        (offset: "-01:00", name: "America/Nuuk"),
        (offset: "-01:00", name: "America/Scoresbysund"),
        (offset: "-01:00", name: "Atlantic/Cape_Verde"),
        (offset: "-02:00", name: "America/Miquelon"),
        (offset: "-02:00", name: "America/Noronha"),
        (offset: "-02:00", name: "Atlantic/South_Georgia"),
        (offset: "-02:30", name: "America/St_Johns"),
        (offset: "-03:00", name: "America/Araguaina"),
        (offset: "-03:00", name: "America/Argentina/Buenos_Aires"),
        (offset: "-03:00", name: "America/Argentina/Catamarca"),
        (offset: "-03:00", name: "America/Argentina/Cordoba"),
        (offset: "-03:00", name: "America/Argentina/Jujuy"),
        (offset: "-03:00", name: "America/Argentina/La_Rioja"),
        (offset: "-03:00", name: "America/Argentina/Mendoza"),
        (offset: "-03:00", name: "America/Argentina/Rio_Gallegos"),
        (offset: "-03:00", name: "America/Argentina/Salta"),
        (offset: "-03:00", name: "America/Argentina/San_Juan"),
        (offset: "-03:00", name: "America/Argentina/San_Luis"),
        (offset: "-03:00", name: "America/Argentina/Tucuman"),
        (offset: "-03:00", name: "America/Argentina/Ushuaia"),
        (offset: "-03:00", name: "America/Asuncion"),
        (offset: "-03:00", name: "America/Bahia"),
        (offset: "-03:00", name: "America/Belem"),
        (offset: "-03:00", name: "America/Cayenne"),
        (offset: "-03:00", name: "America/Coyhaique"),
        (offset: "-03:00", name: "America/Fortaleza"),
        (offset: "-03:00", name: "America/Glace_Bay"),
        (offset: "-03:00", name: "America/Goose_Bay"),
        (offset: "-03:00", name: "America/Halifax"),
        (offset: "-03:00", name: "America/Maceio"),
        (offset: "-03:00", name: "America/Moncton"),
        (offset: "-03:00", name: "America/Montevideo"),
        (offset: "-03:00", name: "America/Paramaribo"),
        (offset: "-03:00", name: "America/Punta_Arenas"),
        (offset: "-03:00", name: "America/Recife"),
        (offset: "-03:00", name: "America/Santarem"),
        (offset: "-03:00", name: "America/Sao_Paulo"),
        (offset: "-03:00", name: "America/Thule"),
        (offset: "-03:00", name: "Antarctica/Palmer"),
        (offset: "-03:00", name: "Antarctica/Rothera"),
        (offset: "-03:00", name: "Atlantic/Bermuda"),
        (offset: "-03:00", name: "Atlantic/Stanley"),
        (offset: "-04:00", name: "America/Anguilla"),
        (offset: "-04:00", name: "America/Antigua"),
        (offset: "-04:00", name: "America/Aruba"),
        (offset: "-04:00", name: "America/Barbados"),
        (offset: "-04:00", name: "America/Blanc-Sablon"),
        (offset: "-04:00", name: "America/Boa_Vista"),
        (offset: "-04:00", name: "America/Campo_Grande"),
        (offset: "-04:00", name: "America/Caracas"),
        (offset: "-04:00", name: "America/Cuiaba"),
        (offset: "-04:00", name: "America/Curacao"),
        (offset: "-04:00", name: "America/Detroit"),
        (offset: "-04:00", name: "America/Dominica"),
        (offset: "-04:00", name: "America/Grand_Turk"),
        (offset: "-04:00", name: "America/Grenada"),
        (offset: "-04:00", name: "America/Guadeloupe"),
        (offset: "-04:00", name: "America/Guyana"),
        (offset: "-04:00", name: "America/Havana"),
        (offset: "-04:00", name: "America/Indiana/Indianapolis"),
        (offset: "-04:00", name: "America/Indiana/Marengo"),
        (offset: "-04:00", name: "America/Indiana/Petersburg"),
        (offset: "-04:00", name: "America/Indiana/Vevay"),
        (offset: "-04:00", name: "America/Indiana/Vincennes"),
        (offset: "-04:00", name: "America/Indiana/Winamac"),
        (offset: "-04:00", name: "America/Iqaluit"),
        (offset: "-04:00", name: "America/Kentucky/Louisville"),
        (offset: "-04:00", name: "America/Kentucky/Monticello"),
        (offset: "-04:00", name: "America/Kralendijk"),
        (offset: "-04:00", name: "America/La_Paz"),
        (offset: "-04:00", name: "America/Lower_Princes"),
        (offset: "-04:00", name: "America/Manaus"),
        (offset: "-04:00", name: "America/Marigot"),
        (offset: "-04:00", name: "America/Martinique"),
        (offset: "-04:00", name: "America/Montserrat"),
        (offset: "-04:00", name: "America/Nassau"),
        (offset: "-04:00", name: "America/New_York"),
        (offset: "-04:00", name: "America/Port_of_Spain"),
        (offset: "-04:00", name: "America/Port-au-Prince"),
        (offset: "-04:00", name: "America/Porto_Velho"),
        (offset: "-04:00", name: "America/Puerto_Rico"),
        (offset: "-04:00", name: "America/Santiago"),
        (offset: "-04:00", name: "America/Santo_Domingo"),
        (offset: "-04:00", name: "America/St_Barthelemy"),
        (offset: "-04:00", name: "America/St_Kitts"),
        (offset: "-04:00", name: "America/St_Lucia"),
        (offset: "-04:00", name: "America/St_Thomas"),
        (offset: "-04:00", name: "America/St_Vincent"),
        (offset: "-04:00", name: "America/Toronto"),
        (offset: "-04:00", name: "America/Tortola"),
        (offset: "-05:00", name: "America/Atikokan"),
        (offset: "-05:00", name: "America/Bogota"),
        (offset: "-05:00", name: "America/Cancun"),
        (offset: "-05:00", name: "America/Cayman"),
        (offset: "-05:00", name: "America/Chicago"),
        (offset: "-05:00", name: "America/Eirunepe"),
        (offset: "-05:00", name: "America/Guayaquil"),
        (offset: "-05:00", name: "America/Indiana/Knox"),
        (offset: "-05:00", name: "America/Indiana/Tell_City"),
        (offset: "-05:00", name: "America/Jamaica"),
        (offset: "-05:00", name: "America/Lima"),
        (offset: "-05:00", name: "America/Matamoros"),
        (offset: "-05:00", name: "America/Menominee"),
        (offset: "-05:00", name: "America/North_Dakota/Beulah"),
        (offset: "-05:00", name: "America/North_Dakota/Center"),
        (offset: "-05:00", name: "America/North_Dakota/New_Salem"),
        (offset: "-05:00", name: "America/Ojinaga"),
        (offset: "-05:00", name: "America/Panama"),
        (offset: "-05:00", name: "America/Rankin_Inlet"),
        (offset: "-05:00", name: "America/Resolute"),
        (offset: "-05:00", name: "America/Rio_Branco"),
        (offset: "-05:00", name: "America/Winnipeg"),
        (offset: "-06:00", name: "America/Bahia_Banderas"),
        (offset: "-06:00", name: "America/Belize"),
        (offset: "-06:00", name: "America/Boise"),
        (offset: "-06:00", name: "America/Cambridge_Bay"),
        (offset: "-06:00", name: "America/Chihuahua"),
        (offset: "-06:00", name: "America/Ciudad_Juarez"),
        (offset: "-06:00", name: "America/Costa_Rica"),
        (offset: "-06:00", name: "America/Denver"),
        (offset: "-06:00", name: "America/Edmonton"),
        (offset: "-06:00", name: "America/El_Salvador"),
        (offset: "-06:00", name: "America/Guatemala"),
        (offset: "-06:00", name: "America/Inuvik"),
        (offset: "-06:00", name: "America/Managua"),
        (offset: "-06:00", name: "America/Merida"),
        (offset: "-06:00", name: "America/Mexico_City"),
        (offset: "-06:00", name: "America/Monterrey"),
        (offset: "-06:00", name: "America/Regina"),
        (offset: "-06:00", name: "America/Swift_Current"),
        (offset: "-06:00", name: "America/Tegucigalpa"),
        (offset: "-06:00", name: "Pacific/Easter"),
        (offset: "-06:00", name: "Pacific/Galapagos"),
        (offset: "-07:00", name: "America/Creston"),
        (offset: "-07:00", name: "America/Dawson"),
        (offset: "-07:00", name: "America/Dawson_Creek"),
        (offset: "-07:00", name: "America/Fort_Nelson"),
        (offset: "-07:00", name: "America/Hermosillo"),
        (offset: "-07:00", name: "America/Los_Angeles"),
        (offset: "-07:00", name: "America/Mazatlan"),
        (offset: "-07:00", name: "America/Phoenix"),
        (offset: "-07:00", name: "America/Tijuana"),
        (offset: "-07:00", name: "America/Vancouver"),
        (offset: "-07:00", name: "America/Whitehorse"),
        (offset: "-08:00", name: "America/Anchorage"),
        (offset: "-08:00", name: "America/Juneau"),
        (offset: "-08:00", name: "America/Metlakatla"),
        (offset: "-08:00", name: "America/Nome"),
        (offset: "-08:00", name: "America/Sitka"),
        (offset: "-08:00", name: "America/Yakutat"),
        (offset: "-08:00", name: "Pacific/Pitcairn"),
        (offset: "-09:00", name: "America/Adak"),
        (offset: "-09:00", name: "Pacific/Gambier"),
        (offset: "-09:30", name: "Pacific/Marquesas"),
        (offset: "-10:00", name: "Pacific/Honolulu"),
        (offset: "-10:00", name: "Pacific/Rarotonga"),
        (offset: "-10:00", name: "Pacific/Tahiti"),
        (offset: "-11:00", name: "Pacific/Midway"),
        (offset: "-11:00", name: "Pacific/Niue"),
        (offset: "-11:00", name: "Pacific/Pago_Pago"),
        (offset: "+00:00", name: "Africa/Abidjan"),
        (offset: "+00:00", name: "Africa/Accra"),
        (offset: "+00:00", name: "Africa/Bamako"),
        (offset: "+00:00", name: "Africa/Banjul"),
        (offset: "+00:00", name: "Africa/Bissau"),
        (offset: "+00:00", name: "Africa/Conakry"),
        (offset: "+00:00", name: "Africa/Dakar"),
        (offset: "+00:00", name: "Africa/Freetown"),
        (offset: "+00:00", name: "Africa/Lome"),
        (offset: "+00:00", name: "Africa/Monrovia"),
        (offset: "+00:00", name: "Africa/Nouakchott"),
        (offset: "+00:00", name: "Africa/Ouagadougou"),
        (offset: "+00:00", name: "Africa/Sao_Tome"),
        (offset: "+00:00", name: "America/Danmarkshavn"),
        (offset: "+00:00", name: "Atlantic/Azores"),
        (offset: "+00:00", name: "Atlantic/Reykjavik"),
        (offset: "+00:00", name: "Atlantic/St_Helena"),
        (offset: "+00:00", name: "UTC"),
        (offset: "+01:00", name: "Africa/Algiers"),
        (offset: "+01:00", name: "Africa/Bangui"),
        (offset: "+01:00", name: "Africa/Brazzaville"),
        (offset: "+01:00", name: "Africa/Casablanca"),
        (offset: "+01:00", name: "Africa/Douala"),
        (offset: "+01:00", name: "Africa/El_Aaiun"),
        (offset: "+01:00", name: "Africa/Kinshasa"),
        (offset: "+01:00", name: "Africa/Lagos"),
        (offset: "+01:00", name: "Africa/Libreville"),
        (offset: "+01:00", name: "Africa/Luanda"),
        (offset: "+01:00", name: "Africa/Malabo"),
        (offset: "+01:00", name: "Africa/Ndjamena"),
        (offset: "+01:00", name: "Africa/Niamey"),
        (offset: "+01:00", name: "Africa/Porto-Novo"),
        (offset: "+01:00", name: "Africa/Tunis"),
        (offset: "+01:00", name: "Atlantic/Canary"),
        (offset: "+01:00", name: "Atlantic/Faroe"),
        (offset: "+01:00", name: "Atlantic/Madeira"),
        (offset: "+01:00", name: "Europe/Dublin"),
        (offset: "+01:00", name: "Europe/Guernsey"),
        (offset: "+01:00", name: "Europe/Isle_of_Man"),
        (offset: "+01:00", name: "Europe/Jersey"),
        (offset: "+01:00", name: "Europe/Lisbon"),
        (offset: "+01:00", name: "Europe/London"),
        (offset: "+02:00", name: "Africa/Blantyre"),
        (offset: "+02:00", name: "Africa/Bujumbura"),
        (offset: "+02:00", name: "Africa/Ceuta"),
        (offset: "+02:00", name: "Africa/Gaborone"),
        (offset: "+02:00", name: "Africa/Harare"),
        (offset: "+02:00", name: "Africa/Johannesburg"),
        (offset: "+02:00", name: "Africa/Juba"),
        (offset: "+02:00", name: "Africa/Khartoum"),
        (offset: "+02:00", name: "Africa/Kigali"),
        (offset: "+02:00", name: "Africa/Lubumbashi"),
        (offset: "+02:00", name: "Africa/Lusaka"),
        (offset: "+02:00", name: "Africa/Maputo"),
        (offset: "+02:00", name: "Africa/Maseru"),
        (offset: "+02:00", name: "Africa/Mbabane"),
        (offset: "+02:00", name: "Africa/Tripoli"),
        (offset: "+02:00", name: "Africa/Windhoek"),
        (offset: "+02:00", name: "Antarctica/Troll"),
        (offset: "+02:00", name: "Arctic/Longyearbyen"),
        (offset: "+02:00", name: "Europe/Amsterdam"),
        (offset: "+02:00", name: "Europe/Andorra"),
        (offset: "+02:00", name: "Europe/Belgrade"),
        (offset: "+02:00", name: "Europe/Berlin"),
        (offset: "+02:00", name: "Europe/Bratislava"),
        (offset: "+02:00", name: "Europe/Brussels"),
        (offset: "+02:00", name: "Europe/Budapest"),
        (offset: "+02:00", name: "Europe/Busingen"),
        (offset: "+02:00", name: "Europe/Copenhagen"),
        (offset: "+02:00", name: "Europe/Gibraltar"),
        (offset: "+02:00", name: "Europe/Kaliningrad"),
        (offset: "+02:00", name: "Europe/Ljubljana"),
        (offset: "+02:00", name: "Europe/Luxembourg"),
        (offset: "+02:00", name: "Europe/Madrid"),
        (offset: "+02:00", name: "Europe/Malta"),
        (offset: "+02:00", name: "Europe/Monaco"),
        (offset: "+02:00", name: "Europe/Oslo"),
        (offset: "+02:00", name: "Europe/Paris"),
        (offset: "+02:00", name: "Europe/Podgorica"),
        (offset: "+02:00", name: "Europe/Prague"),
        (offset: "+02:00", name: "Europe/Rome"),
        (offset: "+02:00", name: "Europe/San_Marino"),
        (offset: "+02:00", name: "Europe/Sarajevo"),
        (offset: "+02:00", name: "Europe/Skopje"),
        (offset: "+02:00", name: "Europe/Stockholm"),
        (offset: "+02:00", name: "Europe/Tirane"),
        (offset: "+02:00", name: "Europe/Vaduz"),
        (offset: "+02:00", name: "Europe/Vatican"),
        (offset: "+02:00", name: "Europe/Vienna"),
        (offset: "+02:00", name: "Europe/Warsaw"),
        (offset: "+02:00", name: "Europe/Zagreb"),
        (offset: "+02:00", name: "Europe/Zurich"),
        (offset: "+03:00", name: "Africa/Addis_Ababa"),
        (offset: "+03:00", name: "Africa/Asmara"),
        (offset: "+03:00", name: "Africa/Cairo"),
        (offset: "+03:00", name: "Africa/Dar_es_Salaam"),
        (offset: "+03:00", name: "Africa/Djibouti"),
        (offset: "+03:00", name: "Africa/Kampala"),
        (offset: "+03:00", name: "Africa/Mogadishu"),
        (offset: "+03:00", name: "Africa/Nairobi"),
        (offset: "+03:00", name: "Antarctica/Syowa"),
        (offset: "+03:00", name: "Asia/Aden"),
        (offset: "+03:00", name: "Asia/Amman"),
        (offset: "+03:00", name: "Asia/Baghdad"),
        (offset: "+03:00", name: "Asia/Bahrain"),
        (offset: "+03:00", name: "Asia/Beirut"),
        (offset: "+03:00", name: "Asia/Damascus"),
        (offset: "+03:00", name: "Asia/Famagusta"),
        (offset: "+03:00", name: "Asia/Gaza"),
        (offset: "+03:00", name: "Asia/Hebron"),
        (offset: "+03:00", name: "Asia/Jerusalem"),
        (offset: "+03:00", name: "Asia/Kuwait"),
        (offset: "+03:00", name: "Asia/Nicosia"),
        (offset: "+03:00", name: "Asia/Qatar"),
        (offset: "+03:00", name: "Asia/Riyadh"),
        (offset: "+03:00", name: "Europe/Athens"),
        (offset: "+03:00", name: "Europe/Bucharest"),
        (offset: "+03:00", name: "Europe/Chisinau"),
        (offset: "+03:00", name: "Europe/Helsinki"),
        (offset: "+03:00", name: "Europe/Istanbul"),
        (offset: "+03:00", name: "Europe/Kirov"),
        (offset: "+03:00", name: "Europe/Kyiv"),
        (offset: "+03:00", name: "Europe/Mariehamn"),
        (offset: "+03:00", name: "Europe/Minsk"),
        (offset: "+03:00", name: "Europe/Moscow"),
        (offset: "+03:00", name: "Europe/Riga"),
        (offset: "+03:00", name: "Europe/Simferopol"),
        (offset: "+03:00", name: "Europe/Sofia"),
        (offset: "+03:00", name: "Europe/Tallinn"),
        (offset: "+03:00", name: "Europe/Vilnius"),
        (offset: "+03:00", name: "Europe/Volgograd"),
        (offset: "+03:00", name: "Indian/Antananarivo"),
        (offset: "+03:00", name: "Indian/Comoro"),
        (offset: "+03:00", name: "Indian/Mayotte"),
        (offset: "+03:30", name: "Asia/Tehran"),
        (offset: "+04:00", name: "Asia/Baku"),
        (offset: "+04:00", name: "Asia/Dubai"),
        (offset: "+04:00", name: "Asia/Muscat"),
        (offset: "+04:00", name: "Asia/Tbilisi"),
        (offset: "+04:00", name: "Asia/Yerevan"),
        (offset: "+04:00", name: "Europe/Astrakhan"),
        (offset: "+04:00", name: "Europe/Samara"),
        (offset: "+04:00", name: "Europe/Saratov"),
        (offset: "+04:00", name: "Europe/Ulyanovsk"),
        (offset: "+04:00", name: "Indian/Mahe"),
        (offset: "+04:00", name: "Indian/Mauritius"),
        (offset: "+04:00", name: "Indian/Reunion"),
        (offset: "+04:30", name: "Asia/Kabul"),
        (offset: "+05:00", name: "Antarctica/Mawson"),
        (offset: "+05:00", name: "Antarctica/Vostok"),
        (offset: "+05:00", name: "Asia/Almaty"),
        (offset: "+05:00", name: "Asia/Aqtau"),
        (offset: "+05:00", name: "Asia/Aqtobe"),
        (offset: "+05:00", name: "Asia/Ashgabat"),
        (offset: "+05:00", name: "Asia/Atyrau"),
        (offset: "+05:00", name: "Asia/Dushanbe"),
        (offset: "+05:00", name: "Asia/Karachi"),
        (offset: "+05:00", name: "Asia/Oral"),
        (offset: "+05:00", name: "Asia/Qostanay"),
        (offset: "+05:00", name: "Asia/Qyzylorda"),
        (offset: "+05:00", name: "Asia/Samarkand"),
        (offset: "+05:00", name: "Asia/Tashkent"),
        (offset: "+05:00", name: "Asia/Yekaterinburg"),
        (offset: "+05:00", name: "Indian/Kerguelen"),
        (offset: "+05:00", name: "Indian/Maldives"),
        (offset: "+05:30", name: "Asia/Colombo"),
        (offset: "+05:30", name: "Asia/Kolkata"),
        (offset: "+05:45", name: "Asia/Kathmandu"),
        (offset: "+06:00", name: "Asia/Bishkek"),
        (offset: "+06:00", name: "Asia/Dhaka"),
        (offset: "+06:00", name: "Asia/Omsk"),
        (offset: "+06:00", name: "Asia/Thimphu"),
        (offset: "+06:00", name: "Asia/Urumqi"),
        (offset: "+06:00", name: "Indian/Chagos"),
        (offset: "+06:30", name: "Asia/Yangon"),
        (offset: "+06:30", name: "Indian/Cocos"),
        (offset: "+07:00", name: "Antarctica/Davis"),
        (offset: "+07:00", name: "Asia/Bangkok"),
        (offset: "+07:00", name: "Asia/Barnaul"),
        (offset: "+07:00", name: "Asia/Ho_Chi_Minh"),
        (offset: "+07:00", name: "Asia/Hovd"),
        (offset: "+07:00", name: "Asia/Jakarta"),
        (offset: "+07:00", name: "Asia/Krasnoyarsk"),
        (offset: "+07:00", name: "Asia/Novokuznetsk"),
        (offset: "+07:00", name: "Asia/Novosibirsk"),
        (offset: "+07:00", name: "Asia/Phnom_Penh"),
        (offset: "+07:00", name: "Asia/Pontianak"),
        (offset: "+07:00", name: "Asia/Tomsk"),
        (offset: "+07:00", name: "Asia/Vientiane"),
        (offset: "+07:00", name: "Indian/Christmas"),
        (offset: "+08:00", name: "Antarctica/Casey"),
        (offset: "+08:00", name: "Asia/Brunei"),
        (offset: "+08:00", name: "Asia/Hong_Kong"),
        (offset: "+08:00", name: "Asia/Irkutsk"),
        (offset: "+08:00", name: "Asia/Kuala_Lumpur"),
        (offset: "+08:00", name: "Asia/Kuching"),
        (offset: "+08:00", name: "Asia/Macau"),
        (offset: "+08:00", name: "Asia/Makassar"),
        (offset: "+08:00", name: "Asia/Manila"),
        (offset: "+08:00", name: "Asia/Shanghai"),
        (offset: "+08:00", name: "Asia/Singapore"),
        (offset: "+08:00", name: "Asia/Taipei"),
        (offset: "+08:00", name: "Asia/Ulaanbaatar"),
        (offset: "+08:00", name: "Australia/Perth"),
        (offset: "+08:45", name: "Australia/Eucla"),
        (offset: "+09:00", name: "Asia/Chita"),
        (offset: "+09:00", name: "Asia/Dili"),
        (offset: "+09:00", name: "Asia/Jayapura"),
        (offset: "+09:00", name: "Asia/Khandyga"),
        (offset: "+09:00", name: "Asia/Pyongyang"),
        (offset: "+09:00", name: "Asia/Seoul"),
        (offset: "+09:00", name: "Asia/Tokyo"),
        (offset: "+09:00", name: "Asia/Yakutsk"),
        (offset: "+09:00", name: "Pacific/Palau"),
        (offset: "+09:30", name: "Australia/Adelaide"),
        (offset: "+09:30", name: "Australia/Broken_Hill"),
        (offset: "+09:30", name: "Australia/Darwin"),
        (offset: "+10:00", name: "Antarctica/DumontDUrville"),
        (offset: "+10:00", name: "Antarctica/Macquarie"),
        (offset: "+10:00", name: "Asia/Ust-Nera"),
        (offset: "+10:00", name: "Asia/Vladivostok"),
        (offset: "+10:00", name: "Australia/Brisbane"),
        (offset: "+10:00", name: "Australia/Hobart"),
        (offset: "+10:00", name: "Australia/Lindeman"),
        (offset: "+10:00", name: "Australia/Melbourne"),
        (offset: "+10:00", name: "Australia/Sydney"),
        (offset: "+10:00", name: "Pacific/Chuuk"),
        (offset: "+10:00", name: "Pacific/Guam"),
        (offset: "+10:00", name: "Pacific/Port_Moresby"),
        (offset: "+10:00", name: "Pacific/Saipan"),
        (offset: "+10:30", name: "Australia/Lord_Howe"),
        (offset: "+11:00", name: "Asia/Magadan"),
        (offset: "+11:00", name: "Asia/Sakhalin"),
        (offset: "+11:00", name: "Asia/Srednekolymsk"),
        (offset: "+11:00", name: "Pacific/Bougainville"),
        (offset: "+11:00", name: "Pacific/Efate"),
        (offset: "+11:00", name: "Pacific/Guadalcanal"),
        (offset: "+11:00", name: "Pacific/Kosrae"),
        (offset: "+11:00", name: "Pacific/Norfolk"),
        (offset: "+11:00", name: "Pacific/Noumea"),
        (offset: "+11:00", name: "Pacific/Pohnpei"),
        (offset: "+12:00", name: "Antarctica/McMurdo"),
        (offset: "+12:00", name: "Asia/Anadyr"),
        (offset: "+12:00", name: "Asia/Kamchatka"),
        (offset: "+12:00", name: "Pacific/Auckland"),
        (offset: "+12:00", name: "Pacific/Fiji"),
        (offset: "+12:00", name: "Pacific/Funafuti"),
        (offset: "+12:00", name: "Pacific/Kwajalein"),
        (offset: "+12:00", name: "Pacific/Majuro"),
        (offset: "+12:00", name: "Pacific/Nauru"),
        (offset: "+12:00", name: "Pacific/Tarawa"),
        (offset: "+12:00", name: "Pacific/Wake"),
        (offset: "+12:00", name: "Pacific/Wallis"),
        (offset: "+12:45", name: "Pacific/Chatham"),
        (offset: "+13:00", name: "Pacific/Apia"),
        (offset: "+13:00", name: "Pacific/Fakaofo"),
        (offset: "+13:00", name: "Pacific/Kanton"),
        (offset: "+13:00", name: "Pacific/Tongatapu"),
        (offset: "+14:00", name: "Pacific/Kiritimati"),
    ]

}
