
/* ############################################################# */
/* ### Copyright © 2026 Maxim Rysevets. All rights reserved. ### */
/* ############################################################# */

import Foundation

extension Date {

    enum Format: String {
        case iso8601         = "yyyy-MM-dd HH:mm:ss"
        case iso8601Timezone = "yyyy-MM-dd HH:mm:ss Z"
        case iso8601Mono     = "yyyyMMdd_HHmmss"
        case convenientDate  = "d MMM yyyy"
        case convenientTime  = "HH:mm:ss"
    }

    var formatConvenient: String {
        let formatter = DateFormatter()
        formatter.dateFormat = String(
            format: NSLocalizedString("%@ 'at' %@", comment: ""),
            Self.Format.convenientDate.rawValue,
            Self.Format.convenientTime.rawValue )
        return formatter.string(from: self)
    }

    var formatISO8601withTZ: String {
        let formatter = DateFormatter()
        formatter.dateFormat = Self.Format.iso8601Timezone.rawValue
        formatter.locale = Locale(identifier: "en_US_POSIX")
        return formatter.string(from: self)
    }

    var formatISO8601: String {
        let formatter = DateFormatter()
        formatter.dateFormat = Self.Format.iso8601Timezone.rawValue
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.timeZone = TimeZone(secondsFromGMT: 0)
        return formatter.string(from: self)
    }

    var formatISO8601Mono: String {
        let formatter = DateFormatter()
        formatter.dateFormat = Self.Format.iso8601Mono.rawValue
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.timeZone = TimeZone(secondsFromGMT: 0)
        let mSec = Int(Self().timeIntervalSince1970.fractionalPart * 1_000)
        return formatter.string(from: self) + "-\(mSec)"
    }

    var day   : Int { get { Calendar.current.component(.day   , from: self) } set { self._updateComponent(day   : newValue) } }
    var month : Int { get { Calendar.current.component(.month , from: self) } set { self._updateComponent(month : newValue) } }
    var year  : Int { get { Calendar.current.component(.year  , from: self) } set { self._updateComponent(year  : newValue) } }
    var hour  : Int { get { Calendar.current.component(.hour  , from: self) } set { self._updateComponent(hour  : newValue) } }
    var minute: Int { get { Calendar.current.component(.minute, from: self) } set { self._updateComponent(minute: newValue) } }
    var second: Int { get { Calendar.current.component(.second, from: self) } set { self._updateComponent(second: newValue) } }

    private mutating func _updateComponent(
        day   : Int? = nil,
        month : Int? = nil,
        year  : Int? = nil,
        hour  : Int? = nil,
        minute: Int? = nil,
        second: Int? = nil,
    ) {
        var components = Calendar.current.dateComponents([
            .day, .month, .year, .hour, .minute, .second
        ], from: self)

        if let day    { components.day    = day }
        if let month  { components.month  = month }
        if let year   { components.year   = year }
        if let hour   { components.hour   = hour }
        if let minute { components.minute = minute }
        if let second { components.second = second }

        if let newDate = Calendar.current.date(from: components) {
            self = newDate
        }
    }

    static public let MONTH_NAMES = [
         1: "January",
         2: "February",
         3: "March",
         4: "April",
         5: "May",
         6: "June",
         7: "July",
         8: "August",
         9: "September",
        10: "October",
        11: "November",
        12: "December",
    ]

    static public let TIME_ZONES: [(offset: String, name: String)] = [
        (offset: "-01:00", name: "America/Nuuk"),
        (offset: "-01:00", name: "America/Scoresbysund"),
        (offset: "-01:00", name: "Atlantic/Cape_Verde"),
        (offset: "-02:00", name: "America/Miquelon"),
        (offset: "-02:00", name: "America/Noronha"),
        (offset: "-02:00", name: "Atlantic/South_Georgia"),
        (offset: "-02:30", name: "America/St_Johns"),
        (offset: "-03:00", name: "America/Araguaina"),
        (offset: "-03:00", name: "America/Argentina/Buenos_Aires"),
        (offset: "-03:00", name: "America/Argentina/Catamarca"),
        (offset: "-03:00", name: "America/Argentina/Cordoba"),
        (offset: "-03:00", name: "America/Argentina/Jujuy"),
        (offset: "-03:00", name: "America/Argentina/La_Rioja"),
        (offset: "-03:00", name: "America/Argentina/Mendoza"),
        (offset: "-03:00", name: "America/Argentina/Rio_Gallegos"),
        (offset: "-03:00", name: "America/Argentina/Salta"),
        (offset: "-03:00", name: "America/Argentina/San_Juan"),
        (offset: "-03:00", name: "America/Argentina/San_Luis"),
        (offset: "-03:00", name: "America/Argentina/Tucuman"),
        (offset: "-03:00", name: "America/Argentina/Ushuaia"),
        (offset: "-03:00", name: "America/Asuncion"),
        (offset: "-03:00", name: "America/Bahia"),
        (offset: "-03:00", name: "America/Belem"),
        (offset: "-03:00", name: "America/Cayenne"),
        (offset: "-03:00", name: "America/Coyhaique"),
        (offset: "-03:00", name: "America/Fortaleza"),
        (offset: "-03:00", name: "America/Glace_Bay"),
        (offset: "-03:00", name: "America/Goose_Bay"),
        (offset: "-03:00", name: "America/Halifax"),
        (offset: "-03:00", name: "America/Maceio"),
        (offset: "-03:00", name: "America/Moncton"),
        (offset: "-03:00", name: "America/Montevideo"),
        (offset: "-03:00", name: "America/Paramaribo"),
        (offset: "-03:00", name: "America/Punta_Arenas"),
        (offset: "-03:00", name: "America/Recife"),
        (offset: "-03:00", name: "America/Santarem"),
        (offset: "-03:00", name: "America/Sao_Paulo"),
        (offset: "-03:00", name: "America/Thule"),
        (offset: "-03:00", name: "Antarctica/Palmer"),
        (offset: "-03:00", name: "Antarctica/Rothera"),
        (offset: "-03:00", name: "Atlantic/Bermuda"),
        (offset: "-03:00", name: "Atlantic/Stanley"),
        (offset: "-04:00", name: "America/Anguilla"),
        (offset: "-04:00", name: "America/Antigua"),
        (offset: "-04:00", name: "America/Aruba"),
        (offset: "-04:00", name: "America/Barbados"),
        (offset: "-04:00", name: "America/Blanc-Sablon"),
        (offset: "-04:00", name: "America/Boa_Vista"),
        (offset: "-04:00", name: "America/Campo_Grande"),
        (offset: "-04:00", name: "America/Caracas"),
        (offset: "-04:00", name: "America/Cuiaba"),
        (offset: "-04:00", name: "America/Curacao"),
        (offset: "-04:00", name: "America/Detroit"),
        (offset: "-04:00", name: "America/Dominica"),
        (offset: "-04:00", name: "America/Grand_Turk"),
        (offset: "-04:00", name: "America/Grenada"),
        (offset: "-04:00", name: "America/Guadeloupe"),
        (offset: "-04:00", name: "America/Guyana"),
        (offset: "-04:00", name: "America/Havana"),
        (offset: "-04:00", name: "America/Indiana/Indianapolis"),
        (offset: "-04:00", name: "America/Indiana/Marengo"),
        (offset: "-04:00", name: "America/Indiana/Petersburg"),
        (offset: "-04:00", name: "America/Indiana/Vevay"),
        (offset: "-04:00", name: "America/Indiana/Vincennes"),
        (offset: "-04:00", name: "America/Indiana/Winamac"),
        (offset: "-04:00", name: "America/Iqaluit"),
        (offset: "-04:00", name: "America/Kentucky/Louisville"),
        (offset: "-04:00", name: "America/Kentucky/Monticello"),
        (offset: "-04:00", name: "America/Kralendijk"),
        (offset: "-04:00", name: "America/La_Paz"),
        (offset: "-04:00", name: "America/Lower_Princes"),
        (offset: "-04:00", name: "America/Manaus"),
        (offset: "-04:00", name: "America/Marigot"),
        (offset: "-04:00", name: "America/Martinique"),
        (offset: "-04:00", name: "America/Montserrat"),
        (offset: "-04:00", name: "America/Nassau"),
        (offset: "-04:00", name: "America/New_York"),
        (offset: "-04:00", name: "America/Port_of_Spain"),
        (offset: "-04:00", name: "America/Port-au-Prince"),
        (offset: "-04:00", name: "America/Porto_Velho"),
        (offset: "-04:00", name: "America/Puerto_Rico"),
        (offset: "-04:00", name: "America/Santiago"),
        (offset: "-04:00", name: "America/Santo_Domingo"),
        (offset: "-04:00", name: "America/St_Barthelemy"),
        (offset: "-04:00", name: "America/St_Kitts"),
        (offset: "-04:00", name: "America/St_Lucia"),
        (offset: "-04:00", name: "America/St_Thomas"),
        (offset: "-04:00", name: "America/St_Vincent"),
        (offset: "-04:00", name: "America/Toronto"),
        (offset: "-04:00", name: "America/Tortola"),
        (offset: "-05:00", name: "America/Atikokan"),
        (offset: "-05:00", name: "America/Bogota"),
        (offset: "-05:00", name: "America/Cancun"),
        (offset: "-05:00", name: "America/Cayman"),
        (offset: "-05:00", name: "America/Chicago"),
        (offset: "-05:00", name: "America/Eirunepe"),
        (offset: "-05:00", name: "America/Guayaquil"),
        (offset: "-05:00", name: "America/Indiana/Knox"),
        (offset: "-05:00", name: "America/Indiana/Tell_City"),
        (offset: "-05:00", name: "America/Jamaica"),
        (offset: "-05:00", name: "America/Lima"),
        (offset: "-05:00", name: "America/Matamoros"),
        (offset: "-05:00", name: "America/Menominee"),
        (offset: "-05:00", name: "America/North_Dakota/Beulah"),
        (offset: "-05:00", name: "America/North_Dakota/Center"),
        (offset: "-05:00", name: "America/North_Dakota/New_Salem"),
        (offset: "-05:00", name: "America/Ojinaga"),
        (offset: "-05:00", name: "America/Panama"),
        (offset: "-05:00", name: "America/Rankin_Inlet"),
        (offset: "-05:00", name: "America/Resolute"),
        (offset: "-05:00", name: "America/Rio_Branco"),
        (offset: "-05:00", name: "America/Winnipeg"),
        (offset: "-06:00", name: "America/Bahia_Banderas"),
        (offset: "-06:00", name: "America/Belize"),
        (offset: "-06:00", name: "America/Boise"),
        (offset: "-06:00", name: "America/Cambridge_Bay"),
        (offset: "-06:00", name: "America/Chihuahua"),
        (offset: "-06:00", name: "America/Ciudad_Juarez"),
        (offset: "-06:00", name: "America/Costa_Rica"),
        (offset: "-06:00", name: "America/Denver"),
        (offset: "-06:00", name: "America/Edmonton"),
        (offset: "-06:00", name: "America/El_Salvador"),
        (offset: "-06:00", name: "America/Guatemala"),
        (offset: "-06:00", name: "America/Inuvik"),
        (offset: "-06:00", name: "America/Managua"),
        (offset: "-06:00", name: "America/Merida"),
        (offset: "-06:00", name: "America/Mexico_City"),
        (offset: "-06:00", name: "America/Monterrey"),
        (offset: "-06:00", name: "America/Regina"),
        (offset: "-06:00", name: "America/Swift_Current"),
        (offset: "-06:00", name: "America/Tegucigalpa"),
        (offset: "-06:00", name: "Pacific/Easter"),
        (offset: "-06:00", name: "Pacific/Galapagos"),
        (offset: "-07:00", name: "America/Creston"),
        (offset: "-07:00", name: "America/Dawson"),
        (offset: "-07:00", name: "America/Dawson_Creek"),
        (offset: "-07:00", name: "America/Fort_Nelson"),
        (offset: "-07:00", name: "America/Hermosillo"),
        (offset: "-07:00", name: "America/Los_Angeles"),
        (offset: "-07:00", name: "America/Mazatlan"),
        (offset: "-07:00", name: "America/Phoenix"),
        (offset: "-07:00", name: "America/Tijuana"),
        (offset: "-07:00", name: "America/Vancouver"),
        (offset: "-07:00", name: "America/Whitehorse"),
        (offset: "-08:00", name: "America/Anchorage"),
        (offset: "-08:00", name: "America/Juneau"),
        (offset: "-08:00", name: "America/Metlakatla"),
        (offset: "-08:00", name: "America/Nome"),
        (offset: "-08:00", name: "America/Sitka"),
        (offset: "-08:00", name: "America/Yakutat"),
        (offset: "-08:00", name: "Pacific/Pitcairn"),
        (offset: "-09:00", name: "America/Adak"),
        (offset: "-09:00", name: "Pacific/Gambier"),
        (offset: "-09:30", name: "Pacific/Marquesas"),
        (offset: "-10:00", name: "Pacific/Honolulu"),
        (offset: "-10:00", name: "Pacific/Rarotonga"),
        (offset: "-10:00", name: "Pacific/Tahiti"),
        (offset: "-11:00", name: "Pacific/Midway"),
        (offset: "-11:00", name: "Pacific/Niue"),
        (offset: "-11:00", name: "Pacific/Pago_Pago"),
        (offset: "+00:00", name: "Africa/Abidjan"),
        (offset: "+00:00", name: "Africa/Accra"),
        (offset: "+00:00", name: "Africa/Bamako"),
        (offset: "+00:00", name: "Africa/Banjul"),
        (offset: "+00:00", name: "Africa/Bissau"),
        (offset: "+00:00", name: "Africa/Conakry"),
        (offset: "+00:00", name: "Africa/Dakar"),
        (offset: "+00:00", name: "Africa/Freetown"),
        (offset: "+00:00", name: "Africa/Lome"),
        (offset: "+00:00", name: "Africa/Monrovia"),
        (offset: "+00:00", name: "Africa/Nouakchott"),
        (offset: "+00:00", name: "Africa/Ouagadougou"),
        (offset: "+00:00", name: "Africa/Sao_Tome"),
        (offset: "+00:00", name: "America/Danmarkshavn"),
        (offset: "+00:00", name: "Atlantic/Azores"),
        (offset: "+00:00", name: "Atlantic/Reykjavik"),
        (offset: "+00:00", name: "Atlantic/St_Helena"),
        (offset: "+00:00", name: "UTC"),
        (offset: "+01:00", name: "Africa/Algiers"),
        (offset: "+01:00", name: "Africa/Bangui"),
        (offset: "+01:00", name: "Africa/Brazzaville"),
        (offset: "+01:00", name: "Africa/Casablanca"),
        (offset: "+01:00", name: "Africa/Douala"),
        (offset: "+01:00", name: "Africa/El_Aaiun"),
        (offset: "+01:00", name: "Africa/Kinshasa"),
        (offset: "+01:00", name: "Africa/Lagos"),
        (offset: "+01:00", name: "Africa/Libreville"),
        (offset: "+01:00", name: "Africa/Luanda"),
        (offset: "+01:00", name: "Africa/Malabo"),
        (offset: "+01:00", name: "Africa/Ndjamena"),
        (offset: "+01:00", name: "Africa/Niamey"),
        (offset: "+01:00", name: "Africa/Porto-Novo"),
        (offset: "+01:00", name: "Africa/Tunis"),
        (offset: "+01:00", name: "Atlantic/Canary"),
        (offset: "+01:00", name: "Atlantic/Faroe"),
        (offset: "+01:00", name: "Atlantic/Madeira"),
        (offset: "+01:00", name: "Europe/Dublin"),
        (offset: "+01:00", name: "Europe/Guernsey"),
        (offset: "+01:00", name: "Europe/Isle_of_Man"),
        (offset: "+01:00", name: "Europe/Jersey"),
        (offset: "+01:00", name: "Europe/Lisbon"),
        (offset: "+01:00", name: "Europe/London"),
        (offset: "+02:00", name: "Africa/Blantyre"),
        (offset: "+02:00", name: "Africa/Bujumbura"),
        (offset: "+02:00", name: "Africa/Ceuta"),
        (offset: "+02:00", name: "Africa/Gaborone"),
        (offset: "+02:00", name: "Africa/Harare"),
        (offset: "+02:00", name: "Africa/Johannesburg"),
        (offset: "+02:00", name: "Africa/Juba"),
        (offset: "+02:00", name: "Africa/Khartoum"),
        (offset: "+02:00", name: "Africa/Kigali"),
        (offset: "+02:00", name: "Africa/Lubumbashi"),
        (offset: "+02:00", name: "Africa/Lusaka"),
        (offset: "+02:00", name: "Africa/Maputo"),
        (offset: "+02:00", name: "Africa/Maseru"),
        (offset: "+02:00", name: "Africa/Mbabane"),
        (offset: "+02:00", name: "Africa/Tripoli"),
        (offset: "+02:00", name: "Africa/Windhoek"),
        (offset: "+02:00", name: "Antarctica/Troll"),
        (offset: "+02:00", name: "Arctic/Longyearbyen"),
        (offset: "+02:00", name: "Europe/Amsterdam"),
        (offset: "+02:00", name: "Europe/Andorra"),
        (offset: "+02:00", name: "Europe/Belgrade"),
        (offset: "+02:00", name: "Europe/Berlin"),
        (offset: "+02:00", name: "Europe/Bratislava"),
        (offset: "+02:00", name: "Europe/Brussels"),
        (offset: "+02:00", name: "Europe/Budapest"),
        (offset: "+02:00", name: "Europe/Busingen"),
        (offset: "+02:00", name: "Europe/Copenhagen"),
        (offset: "+02:00", name: "Europe/Gibraltar"),
        (offset: "+02:00", name: "Europe/Kaliningrad"),
        (offset: "+02:00", name: "Europe/Ljubljana"),
        (offset: "+02:00", name: "Europe/Luxembourg"),
        (offset: "+02:00", name: "Europe/Madrid"),
        (offset: "+02:00", name: "Europe/Malta"),
        (offset: "+02:00", name: "Europe/Monaco"),
        (offset: "+02:00", name: "Europe/Oslo"),
        (offset: "+02:00", name: "Europe/Paris"),
        (offset: "+02:00", name: "Europe/Podgorica"),
        (offset: "+02:00", name: "Europe/Prague"),
        (offset: "+02:00", name: "Europe/Rome"),
        (offset: "+02:00", name: "Europe/San_Marino"),
        (offset: "+02:00", name: "Europe/Sarajevo"),
        (offset: "+02:00", name: "Europe/Skopje"),
        (offset: "+02:00", name: "Europe/Stockholm"),
        (offset: "+02:00", name: "Europe/Tirane"),
        (offset: "+02:00", name: "Europe/Vaduz"),
        (offset: "+02:00", name: "Europe/Vatican"),
        (offset: "+02:00", name: "Europe/Vienna"),
        (offset: "+02:00", name: "Europe/Warsaw"),
        (offset: "+02:00", name: "Europe/Zagreb"),
        (offset: "+02:00", name: "Europe/Zurich"),
        (offset: "+03:00", name: "Africa/Addis_Ababa"),
        (offset: "+03:00", name: "Africa/Asmara"),
        (offset: "+03:00", name: "Africa/Cairo"),
        (offset: "+03:00", name: "Africa/Dar_es_Salaam"),
        (offset: "+03:00", name: "Africa/Djibouti"),
        (offset: "+03:00", name: "Africa/Kampala"),
        (offset: "+03:00", name: "Africa/Mogadishu"),
        (offset: "+03:00", name: "Africa/Nairobi"),
        (offset: "+03:00", name: "Antarctica/Syowa"),
        (offset: "+03:00", name: "Asia/Aden"),
        (offset: "+03:00", name: "Asia/Amman"),
        (offset: "+03:00", name: "Asia/Baghdad"),
        (offset: "+03:00", name: "Asia/Bahrain"),
        (offset: "+03:00", name: "Asia/Beirut"),
        (offset: "+03:00", name: "Asia/Damascus"),
        (offset: "+03:00", name: "Asia/Famagusta"),
        (offset: "+03:00", name: "Asia/Gaza"),
        (offset: "+03:00", name: "Asia/Hebron"),
        (offset: "+03:00", name: "Asia/Jerusalem"),
        (offset: "+03:00", name: "Asia/Kuwait"),
        (offset: "+03:00", name: "Asia/Nicosia"),
        (offset: "+03:00", name: "Asia/Qatar"),
        (offset: "+03:00", name: "Asia/Riyadh"),
        (offset: "+03:00", name: "Europe/Athens"),
        (offset: "+03:00", name: "Europe/Bucharest"),
        (offset: "+03:00", name: "Europe/Chisinau"),
        (offset: "+03:00", name: "Europe/Helsinki"),
        (offset: "+03:00", name: "Europe/Istanbul"),
        (offset: "+03:00", name: "Europe/Kirov"),
        (offset: "+03:00", name: "Europe/Kyiv"),
        (offset: "+03:00", name: "Europe/Mariehamn"),
        (offset: "+03:00", name: "Europe/Minsk"),
        (offset: "+03:00", name: "Europe/Moscow"),
        (offset: "+03:00", name: "Europe/Riga"),
        (offset: "+03:00", name: "Europe/Simferopol"),
        (offset: "+03:00", name: "Europe/Sofia"),
        (offset: "+03:00", name: "Europe/Tallinn"),
        (offset: "+03:00", name: "Europe/Vilnius"),
        (offset: "+03:00", name: "Europe/Volgograd"),
        (offset: "+03:00", name: "Indian/Antananarivo"),
        (offset: "+03:00", name: "Indian/Comoro"),
        (offset: "+03:00", name: "Indian/Mayotte"),
        (offset: "+03:30", name: "Asia/Tehran"),
        (offset: "+04:00", name: "Asia/Baku"),
        (offset: "+04:00", name: "Asia/Dubai"),
        (offset: "+04:00", name: "Asia/Muscat"),
        (offset: "+04:00", name: "Asia/Tbilisi"),
        (offset: "+04:00", name: "Asia/Yerevan"),
        (offset: "+04:00", name: "Europe/Astrakhan"),
        (offset: "+04:00", name: "Europe/Samara"),
        (offset: "+04:00", name: "Europe/Saratov"),
        (offset: "+04:00", name: "Europe/Ulyanovsk"),
        (offset: "+04:00", name: "Indian/Mahe"),
        (offset: "+04:00", name: "Indian/Mauritius"),
        (offset: "+04:00", name: "Indian/Reunion"),
        (offset: "+04:30", name: "Asia/Kabul"),
        (offset: "+05:00", name: "Antarctica/Mawson"),
        (offset: "+05:00", name: "Antarctica/Vostok"),
        (offset: "+05:00", name: "Asia/Almaty"),
        (offset: "+05:00", name: "Asia/Aqtau"),
        (offset: "+05:00", name: "Asia/Aqtobe"),
        (offset: "+05:00", name: "Asia/Ashgabat"),
        (offset: "+05:00", name: "Asia/Atyrau"),
        (offset: "+05:00", name: "Asia/Dushanbe"),
        (offset: "+05:00", name: "Asia/Karachi"),
        (offset: "+05:00", name: "Asia/Oral"),
        (offset: "+05:00", name: "Asia/Qostanay"),
        (offset: "+05:00", name: "Asia/Qyzylorda"),
        (offset: "+05:00", name: "Asia/Samarkand"),
        (offset: "+05:00", name: "Asia/Tashkent"),
        (offset: "+05:00", name: "Asia/Yekaterinburg"),
        (offset: "+05:00", name: "Indian/Kerguelen"),
        (offset: "+05:00", name: "Indian/Maldives"),
        (offset: "+05:30", name: "Asia/Colombo"),
        (offset: "+05:30", name: "Asia/Kolkata"),
        (offset: "+05:45", name: "Asia/Kathmandu"),
        (offset: "+06:00", name: "Asia/Bishkek"),
        (offset: "+06:00", name: "Asia/Dhaka"),
        (offset: "+06:00", name: "Asia/Omsk"),
        (offset: "+06:00", name: "Asia/Thimphu"),
        (offset: "+06:00", name: "Asia/Urumqi"),
        (offset: "+06:00", name: "Indian/Chagos"),
        (offset: "+06:30", name: "Asia/Yangon"),
        (offset: "+06:30", name: "Indian/Cocos"),
        (offset: "+07:00", name: "Antarctica/Davis"),
        (offset: "+07:00", name: "Asia/Bangkok"),
        (offset: "+07:00", name: "Asia/Barnaul"),
        (offset: "+07:00", name: "Asia/Ho_Chi_Minh"),
        (offset: "+07:00", name: "Asia/Hovd"),
        (offset: "+07:00", name: "Asia/Jakarta"),
        (offset: "+07:00", name: "Asia/Krasnoyarsk"),
        (offset: "+07:00", name: "Asia/Novokuznetsk"),
        (offset: "+07:00", name: "Asia/Novosibirsk"),
        (offset: "+07:00", name: "Asia/Phnom_Penh"),
        (offset: "+07:00", name: "Asia/Pontianak"),
        (offset: "+07:00", name: "Asia/Tomsk"),
        (offset: "+07:00", name: "Asia/Vientiane"),
        (offset: "+07:00", name: "Indian/Christmas"),
        (offset: "+08:00", name: "Antarctica/Casey"),
        (offset: "+08:00", name: "Asia/Brunei"),
        (offset: "+08:00", name: "Asia/Hong_Kong"),
        (offset: "+08:00", name: "Asia/Irkutsk"),
        (offset: "+08:00", name: "Asia/Kuala_Lumpur"),
        (offset: "+08:00", name: "Asia/Kuching"),
        (offset: "+08:00", name: "Asia/Macau"),
        (offset: "+08:00", name: "Asia/Makassar"),
        (offset: "+08:00", name: "Asia/Manila"),
        (offset: "+08:00", name: "Asia/Shanghai"),
        (offset: "+08:00", name: "Asia/Singapore"),
        (offset: "+08:00", name: "Asia/Taipei"),
        (offset: "+08:00", name: "Asia/Ulaanbaatar"),
        (offset: "+08:00", name: "Australia/Perth"),
        (offset: "+08:45", name: "Australia/Eucla"),
        (offset: "+09:00", name: "Asia/Chita"),
        (offset: "+09:00", name: "Asia/Dili"),
        (offset: "+09:00", name: "Asia/Jayapura"),
        (offset: "+09:00", name: "Asia/Khandyga"),
        (offset: "+09:00", name: "Asia/Pyongyang"),
        (offset: "+09:00", name: "Asia/Seoul"),
        (offset: "+09:00", name: "Asia/Tokyo"),
        (offset: "+09:00", name: "Asia/Yakutsk"),
        (offset: "+09:00", name: "Pacific/Palau"),
        (offset: "+09:30", name: "Australia/Adelaide"),
        (offset: "+09:30", name: "Australia/Broken_Hill"),
        (offset: "+09:30", name: "Australia/Darwin"),
        (offset: "+10:00", name: "Antarctica/DumontDUrville"),
        (offset: "+10:00", name: "Antarctica/Macquarie"),
        (offset: "+10:00", name: "Asia/Ust-Nera"),
        (offset: "+10:00", name: "Asia/Vladivostok"),
        (offset: "+10:00", name: "Australia/Brisbane"),
        (offset: "+10:00", name: "Australia/Hobart"),
        (offset: "+10:00", name: "Australia/Lindeman"),
        (offset: "+10:00", name: "Australia/Melbourne"),
        (offset: "+10:00", name: "Australia/Sydney"),
        (offset: "+10:00", name: "Pacific/Chuuk"),
        (offset: "+10:00", name: "Pacific/Guam"),
        (offset: "+10:00", name: "Pacific/Port_Moresby"),
        (offset: "+10:00", name: "Pacific/Saipan"),
        (offset: "+10:30", name: "Australia/Lord_Howe"),
        (offset: "+11:00", name: "Asia/Magadan"),
        (offset: "+11:00", name: "Asia/Sakhalin"),
        (offset: "+11:00", name: "Asia/Srednekolymsk"),
        (offset: "+11:00", name: "Pacific/Bougainville"),
        (offset: "+11:00", name: "Pacific/Efate"),
        (offset: "+11:00", name: "Pacific/Guadalcanal"),
        (offset: "+11:00", name: "Pacific/Kosrae"),
        (offset: "+11:00", name: "Pacific/Norfolk"),
        (offset: "+11:00", name: "Pacific/Noumea"),
        (offset: "+11:00", name: "Pacific/Pohnpei"),
        (offset: "+12:00", name: "Antarctica/McMurdo"),
        (offset: "+12:00", name: "Asia/Anadyr"),
        (offset: "+12:00", name: "Asia/Kamchatka"),
        (offset: "+12:00", name: "Pacific/Auckland"),
        (offset: "+12:00", name: "Pacific/Fiji"),
        (offset: "+12:00", name: "Pacific/Funafuti"),
        (offset: "+12:00", name: "Pacific/Kwajalein"),
        (offset: "+12:00", name: "Pacific/Majuro"),
        (offset: "+12:00", name: "Pacific/Nauru"),
        (offset: "+12:00", name: "Pacific/Tarawa"),
        (offset: "+12:00", name: "Pacific/Wake"),
        (offset: "+12:00", name: "Pacific/Wallis"),
        (offset: "+12:45", name: "Pacific/Chatham"),
        (offset: "+13:00", name: "Pacific/Apia"),
        (offset: "+13:00", name: "Pacific/Fakaofo"),
        (offset: "+13:00", name: "Pacific/Kanton"),
        (offset: "+13:00", name: "Pacific/Tongatapu"),
        (offset: "+14:00", name: "Pacific/Kiritimati"),
    ]

    static public let TIME_ZONES_BY_OFFSET: [Int: (formattedOffset: String, items: [String: String])] = [
        50400: (
            formattedOffset: "+14:00",
            items: [
                "Pacific/Kiritimati": "Pacific / Kiritimati",
            ]),
        46800: (
            formattedOffset: "+13:00",
            items: [
                "Pacific/Apia": "Pacific / Apia",
                "Pacific/Fakaofo": "Pacific / Fakaofo",
                "Pacific/Kanton": "Pacific / Kanton",
                "Pacific/Tongatapu": "Pacific / Tongatapu",
            ]),
        45900: (
            formattedOffset: "+12:45",
            items: [
                "Pacific/Chatham": "Pacific / Chatham",
            ]),
        43200: (
            formattedOffset: "+12:00",
            items: [
                "Antarctica/McMurdo": "Antarctica / McMurdo",
                "Asia/Anadyr": "Asia / Anadyr",
                "Asia/Kamchatka": "Asia / Kamchatka",
                "Pacific/Auckland": "Pacific / Auckland",
                "Pacific/Fiji": "Pacific / Fiji",
                "Pacific/Funafuti": "Pacific / Funafuti",
                "Pacific/Kwajalein": "Pacific / Kwajalein",
                "Pacific/Majuro": "Pacific / Majuro",
                "Pacific/Nauru": "Pacific / Nauru",
                "Pacific/Tarawa": "Pacific / Tarawa",
                "Pacific/Wake": "Pacific / Wake",
                "Pacific/Wallis": "Pacific / Wallis",
            ]),
        39600: (
            formattedOffset: "+11:00",
            items: [
                "Asia/Magadan": "Asia / Magadan",
                "Asia/Sakhalin": "Asia / Sakhalin",
                "Asia/Srednekolymsk": "Asia / Srednekolymsk",
                "Pacific/Bougainville": "Pacific / Bougainville",
                "Pacific/Efate": "Pacific / Efate",
                "Pacific/Guadalcanal": "Pacific / Guadalcanal",
                "Pacific/Kosrae": "Pacific / Kosrae",
                "Pacific/Norfolk": "Pacific / Norfolk",
                "Pacific/Noumea": "Pacific / Noumea",
                "Pacific/Pohnpei": "Pacific / Pohnpei",
            ]),
        37800: (
            formattedOffset: "+10:30",
            items: [
                "Australia/Lord_Howe": "Australia / Lord-Howe",
            ]),
        36000: (
            formattedOffset: "+10:00",
            items: [
                "Antarctica/DumontDUrville": "Antarctica / DumontDUrville",
                "Antarctica/Macquarie": "Antarctica / Macquarie",
                "Asia/Ust-Nera": "Asia / Ust-Nera",
                "Asia/Vladivostok": "Asia / Vladivostok",
                "Australia/Brisbane": "Australia / Brisbane",
                "Australia/Hobart": "Australia / Hobart",
                "Australia/Lindeman": "Australia / Lindeman",
                "Australia/Melbourne": "Australia / Melbourne",
                "Australia/Sydney": "Australia / Sydney",
                "Pacific/Chuuk": "Pacific / Chuuk",
                "Pacific/Guam": "Pacific / Guam",
                "Pacific/Port_Moresby": "Pacific / Port-Moresby",
                "Pacific/Saipan": "Pacific / Saipan",
            ]),
        34200: (
            formattedOffset: "+09:30",
            items: [
                "Australia/Adelaide": "Australia / Adelaide",
                "Australia/Broken_Hill": "Australia / Broken-Hill",
                "Australia/Darwin": "Australia / Darwin",
            ]),
        32400: (
            formattedOffset: "+09:00",
            items: [
                "Asia/Chita": "Asia / Chita",
                "Asia/Dili": "Asia / Dili",
                "Asia/Jayapura": "Asia / Jayapura",
                "Asia/Khandyga": "Asia / Khandyga",
                "Asia/Pyongyang": "Asia / Pyongyang",
                "Asia/Seoul": "Asia / Seoul",
                "Asia/Tokyo": "Asia / Tokyo",
                "Asia/Yakutsk": "Asia / Yakutsk",
                "Pacific/Palau": "Pacific / Palau",
            ]),
        31500: (
            formattedOffset: "+08:45",
            items: [
                "Australia/Eucla": "Australia / Eucla",
            ]),
        28800: (
            formattedOffset: "+08:00",
            items: [
                "Antarctica/Casey": "Antarctica / Casey",
                "Asia/Brunei": "Asia / Brunei",
                "Asia/Hong_Kong": "Asia / Hong-Kong",
                "Asia/Irkutsk": "Asia / Irkutsk",
                "Asia/Kuala_Lumpur": "Asia / Kuala-Lumpur",
                "Asia/Kuching": "Asia / Kuching",
                "Asia/Macau": "Asia / Macau",
                "Asia/Makassar": "Asia / Makassar",
                "Asia/Manila": "Asia / Manila",
                "Asia/Shanghai": "Asia / Shanghai",
                "Asia/Singapore": "Asia / Singapore",
                "Asia/Taipei": "Asia / Taipei",
                "Asia/Ulaanbaatar": "Asia / Ulaanbaatar",
                "Australia/Perth": "Australia / Perth",
            ]),
        25200: (
            formattedOffset: "+07:00",
            items: [
                "Antarctica/Davis": "Antarctica / Davis",
                "Asia/Bangkok": "Asia / Bangkok",
                "Asia/Barnaul": "Asia / Barnaul",
                "Asia/Ho_Chi_Minh": "Asia / Ho-Chi-Minh",
                "Asia/Hovd": "Asia / Hovd",
                "Asia/Jakarta": "Asia / Jakarta",
                "Asia/Krasnoyarsk": "Asia / Krasnoyarsk",
                "Asia/Novokuznetsk": "Asia / Novokuznetsk",
                "Asia/Novosibirsk": "Asia / Novosibirsk",
                "Asia/Phnom_Penh": "Asia / Phnom-Penh",
                "Asia/Pontianak": "Asia / Pontianak",
                "Asia/Tomsk": "Asia / Tomsk",
                "Asia/Vientiane": "Asia / Vientiane",
                "Indian/Christmas": "Indian / Christmas",
            ]),
        23400: (
            formattedOffset: "+06:30",
            items: [
                "Asia/Yangon": "Asia / Yangon",
                "Indian/Cocos": "Indian / Cocos",
            ]),
        21600: (
            formattedOffset: "+06:00",
            items: [
                "Asia/Bishkek": "Asia / Bishkek",
                "Asia/Dhaka": "Asia / Dhaka",
                "Asia/Omsk": "Asia / Omsk",
                "Asia/Thimphu": "Asia / Thimphu",
                "Asia/Urumqi": "Asia / Urumqi",
                "Indian/Chagos": "Indian / Chagos",
            ]),
        20700: (
            formattedOffset: "+05:45",
            items: [
                "Asia/Kathmandu": "Asia / Kathmandu",
            ]),
        19800: (
            formattedOffset: "+05:30",
            items: [
                "Asia/Colombo": "Asia / Colombo",
                "Asia/Kolkata": "Asia / Kolkata",
            ]),
        18000: (
            formattedOffset: "+05:00",
            items: [
                "Antarctica/Mawson": "Antarctica / Mawson",
                "Antarctica/Vostok": "Antarctica / Vostok",
                "Asia/Almaty": "Asia / Almaty",
                "Asia/Aqtau": "Asia / Aqtau",
                "Asia/Aqtobe": "Asia / Aqtobe",
                "Asia/Ashgabat": "Asia / Ashgabat",
                "Asia/Atyrau": "Asia / Atyrau",
                "Asia/Dushanbe": "Asia / Dushanbe",
                "Asia/Karachi": "Asia / Karachi",
                "Asia/Oral": "Asia / Oral",
                "Asia/Qostanay": "Asia / Qostanay",
                "Asia/Qyzylorda": "Asia / Qyzylorda",
                "Asia/Samarkand": "Asia / Samarkand",
                "Asia/Tashkent": "Asia / Tashkent",
                "Asia/Yekaterinburg": "Asia / Yekaterinburg",
                "Indian/Kerguelen": "Indian / Kerguelen",
                "Indian/Maldives": "Indian / Maldives",
            ]),
        16200: (
            formattedOffset: "+04:30",
            items: [
                "Asia/Kabul": "Asia / Kabul",
            ]),
        14400: (
            formattedOffset: "+04:00",
            items: [
                "Asia/Baku": "Asia / Baku",
                "Asia/Dubai": "Asia / Dubai",
                "Asia/Muscat": "Asia / Muscat",
                "Asia/Tbilisi": "Asia / Tbilisi",
                "Asia/Yerevan": "Asia / Yerevan",
                "Europe/Astrakhan": "Europe / Astrakhan",
                "Europe/Samara": "Europe / Samara",
                "Europe/Saratov": "Europe / Saratov",
                "Europe/Ulyanovsk": "Europe / Ulyanovsk",
                "Indian/Mahe": "Indian / Mahe",
                "Indian/Mauritius": "Indian / Mauritius",
                "Indian/Reunion": "Indian / Reunion",
            ]),
        12600: (
            formattedOffset: "+03:30",
            items: [
                "Asia/Tehran": "Asia / Tehran",
            ]),
        10800: (
            formattedOffset: "+03:00",
            items: [
                "Africa/Addis_Ababa": "Africa / Addis-Ababa",
                "Africa/Asmara": "Africa / Asmara",
                "Africa/Cairo": "Africa / Cairo",
                "Africa/Dar_es_Salaam": "Africa / Dar-es-Salaam",
                "Africa/Djibouti": "Africa / Djibouti",
                "Africa/Kampala": "Africa / Kampala",
                "Africa/Mogadishu": "Africa / Mogadishu",
                "Africa/Nairobi": "Africa / Nairobi",
                "Antarctica/Syowa": "Antarctica / Syowa",
                "Asia/Aden": "Asia / Aden",
                "Asia/Amman": "Asia / Amman",
                "Asia/Baghdad": "Asia / Baghdad",
                "Asia/Bahrain": "Asia / Bahrain",
                "Asia/Beirut": "Asia / Beirut",
                "Asia/Damascus": "Asia / Damascus",
                "Asia/Famagusta": "Asia / Famagusta",
                "Asia/Gaza": "Asia / Gaza",
                "Asia/Hebron": "Asia / Hebron",
                "Asia/Jerusalem": "Asia / Jerusalem",
                "Asia/Kuwait": "Asia / Kuwait",
                "Asia/Nicosia": "Asia / Nicosia",
                "Asia/Qatar": "Asia / Qatar",
                "Asia/Riyadh": "Asia / Riyadh",
                "Europe/Athens": "Europe / Athens",
                "Europe/Bucharest": "Europe / Bucharest",
                "Europe/Chisinau": "Europe / Chisinau",
                "Europe/Helsinki": "Europe / Helsinki",
                "Europe/Istanbul": "Europe / Istanbul",
                "Europe/Kirov": "Europe / Kirov",
                "Europe/Kyiv": "Europe / Kyiv",
                "Europe/Mariehamn": "Europe / Mariehamn",
                "Europe/Minsk": "Europe / Minsk",
                "Europe/Moscow": "Europe / Moscow",
                "Europe/Riga": "Europe / Riga",
                "Europe/Simferopol": "Europe / Simferopol",
                "Europe/Sofia": "Europe / Sofia",
                "Europe/Tallinn": "Europe / Tallinn",
                "Europe/Vilnius": "Europe / Vilnius",
                "Europe/Volgograd": "Europe / Volgograd",
                "Indian/Antananarivo": "Indian / Antananarivo",
                "Indian/Comoro": "Indian / Comoro",
                "Indian/Mayotte": "Indian / Mayotte",
            ]),
        7200: (
            formattedOffset: "+02:00",
            items: [
                "Africa/Blantyre": "Africa / Blantyre",
                "Africa/Bujumbura": "Africa / Bujumbura",
                "Africa/Ceuta": "Africa / Ceuta",
                "Africa/Gaborone": "Africa / Gaborone",
                "Africa/Harare": "Africa / Harare",
                "Africa/Johannesburg": "Africa / Johannesburg",
                "Africa/Juba": "Africa / Juba",
                "Africa/Khartoum": "Africa / Khartoum",
                "Africa/Kigali": "Africa / Kigali",
                "Africa/Lubumbashi": "Africa / Lubumbashi",
                "Africa/Lusaka": "Africa / Lusaka",
                "Africa/Maputo": "Africa / Maputo",
                "Africa/Maseru": "Africa / Maseru",
                "Africa/Mbabane": "Africa / Mbabane",
                "Africa/Tripoli": "Africa / Tripoli",
                "Africa/Windhoek": "Africa / Windhoek",
                "Antarctica/Troll": "Antarctica / Troll",
                "Arctic/Longyearbyen": "Arctic / Longyearbyen",
                "Europe/Amsterdam": "Europe / Amsterdam",
                "Europe/Andorra": "Europe / Andorra",
                "Europe/Belgrade": "Europe / Belgrade",
                "Europe/Berlin": "Europe / Berlin",
                "Europe/Bratislava": "Europe / Bratislava",
                "Europe/Brussels": "Europe / Brussels",
                "Europe/Budapest": "Europe / Budapest",
                "Europe/Busingen": "Europe / Busingen",
                "Europe/Copenhagen": "Europe / Copenhagen",
                "Europe/Gibraltar": "Europe / Gibraltar",
                "Europe/Kaliningrad": "Europe / Kaliningrad",
                "Europe/Ljubljana": "Europe / Ljubljana",
                "Europe/Luxembourg": "Europe / Luxembourg",
                "Europe/Madrid": "Europe / Madrid",
                "Europe/Malta": "Europe / Malta",
                "Europe/Monaco": "Europe / Monaco",
                "Europe/Oslo": "Europe / Oslo",
                "Europe/Paris": "Europe / Paris",
                "Europe/Podgorica": "Europe / Podgorica",
                "Europe/Prague": "Europe / Prague",
                "Europe/Rome": "Europe / Rome",
                "Europe/San_Marino": "Europe / San-Marino",
                "Europe/Sarajevo": "Europe / Sarajevo",
                "Europe/Skopje": "Europe / Skopje",
                "Europe/Stockholm": "Europe / Stockholm",
                "Europe/Tirane": "Europe / Tirane",
                "Europe/Vaduz": "Europe / Vaduz",
                "Europe/Vatican": "Europe / Vatican",
                "Europe/Vienna": "Europe / Vienna",
                "Europe/Warsaw": "Europe / Warsaw",
                "Europe/Zagreb": "Europe / Zagreb",
                "Europe/Zurich": "Europe / Zurich",
            ]),
        3600: (
            formattedOffset: "+01:00",
            items: [
                "Africa/Algiers": "Africa / Algiers",
                "Africa/Bangui": "Africa / Bangui",
                "Africa/Brazzaville": "Africa / Brazzaville",
                "Africa/Casablanca": "Africa / Casablanca",
                "Africa/Douala": "Africa / Douala",
                "Africa/El_Aaiun": "Africa / El-Aaiun",
                "Africa/Kinshasa": "Africa / Kinshasa",
                "Africa/Lagos": "Africa / Lagos",
                "Africa/Libreville": "Africa / Libreville",
                "Africa/Luanda": "Africa / Luanda",
                "Africa/Malabo": "Africa / Malabo",
                "Africa/Ndjamena": "Africa / Ndjamena",
                "Africa/Niamey": "Africa / Niamey",
                "Africa/Porto-Novo": "Africa / Porto-Novo",
                "Africa/Tunis": "Africa / Tunis",
                "Atlantic/Canary": "Atlantic / Canary",
                "Atlantic/Faroe": "Atlantic / Faroe",
                "Atlantic/Madeira": "Atlantic / Madeira",
                "Europe/Dublin": "Europe / Dublin",
                "Europe/Guernsey": "Europe / Guernsey",
                "Europe/Isle_of_Man": "Europe / Isle-of-Man",
                "Europe/Jersey": "Europe / Jersey",
                "Europe/Lisbon": "Europe / Lisbon",
                "Europe/London": "Europe / London",
            ]),
        0: (
            formattedOffset: "+00:00",
            items: [
                "Africa/Abidjan": "Africa / Abidjan",
                "Africa/Accra": "Africa / Accra",
                "Africa/Bamako": "Africa / Bamako",
                "Africa/Banjul": "Africa / Banjul",
                "Africa/Bissau": "Africa / Bissau",
                "Africa/Conakry": "Africa / Conakry",
                "Africa/Dakar": "Africa / Dakar",
                "Africa/Freetown": "Africa / Freetown",
                "Africa/Lome": "Africa / Lome",
                "Africa/Monrovia": "Africa / Monrovia",
                "Africa/Nouakchott": "Africa / Nouakchott",
                "Africa/Ouagadougou": "Africa / Ouagadougou",
                "Africa/Sao_Tome": "Africa / Sao-Tome",
                "America/Danmarkshavn": "America / Danmarkshavn",
                "Atlantic/Azores": "Atlantic / Azores",
                "Atlantic/Reykjavik": "Atlantic / Reykjavik",
                "Atlantic/St_Helena": "Atlantic / St-Helena",
                "UTC": "UTC",
            ]),
        -3600: (
            formattedOffset: "−01:00",
            items: [
                "America/Nuuk": "America / Nuuk",
                "America/Scoresbysund": "America / Scoresbysund",
                "Atlantic/Cape_Verde": "Atlantic / Cape-Verde",
            ]),
        -7200: (
            formattedOffset: "−02:00",
            items: [
                "America/Miquelon": "America / Miquelon",
                "America/Noronha": "America / Noronha",
                "Atlantic/South_Georgia": "Atlantic / South-Georgia",
            ]),
        -9000: (
            formattedOffset: "−02:30",
            items: [
                "America/St_Johns": "America / St-Johns",
            ]),
        -10800: (
            formattedOffset: "−03:00",
            items: [
                "America/Araguaina": "America / Araguaina",
                "America/Argentina/Buenos_Aires": "America / Argentina / Buenos-Aires",
                "America/Argentina/Catamarca": "America / Argentina / Catamarca",
                "America/Argentina/Cordoba": "America / Argentina / Cordoba",
                "America/Argentina/Jujuy": "America / Argentina / Jujuy",
                "America/Argentina/La_Rioja": "America / Argentina / La-Rioja",
                "America/Argentina/Mendoza": "America / Argentina / Mendoza",
                "America/Argentina/Rio_Gallegos": "America / Argentina / Rio-Gallegos",
                "America/Argentina/Salta": "America / Argentina / Salta",
                "America/Argentina/San_Juan": "America / Argentina / San-Juan",
                "America/Argentina/San_Luis": "America / Argentina / San-Luis",
                "America/Argentina/Tucuman": "America / Argentina / Tucuman",
                "America/Argentina/Ushuaia": "America / Argentina / Ushuaia",
                "America/Asuncion": "America / Asuncion",
                "America/Bahia": "America / Bahia",
                "America/Belem": "America / Belem",
                "America/Cayenne": "America / Cayenne",
                "America/Coyhaique": "America / Coyhaique",
                "America/Fortaleza": "America / Fortaleza",
                "America/Glace_Bay": "America / Glace-Bay",
                "America/Goose_Bay": "America / Goose-Bay",
                "America/Halifax": "America / Halifax",
                "America/Maceio": "America / Maceio",
                "America/Moncton": "America / Moncton",
                "America/Montevideo": "America / Montevideo",
                "America/Paramaribo": "America / Paramaribo",
                "America/Punta_Arenas": "America / Punta-Arenas",
                "America/Recife": "America / Recife",
                "America/Santarem": "America / Santarem",
                "America/Sao_Paulo": "America / Sao-Paulo",
                "America/Thule": "America / Thule",
                "Antarctica/Palmer": "Antarctica / Palmer",
                "Antarctica/Rothera": "Antarctica / Rothera",
                "Atlantic/Bermuda": "Atlantic / Bermuda",
                "Atlantic/Stanley": "Atlantic / Stanley",
            ]),
        -14400: (
            formattedOffset: "−04:00",
            items: [
                "America/Anguilla": "America / Anguilla",
                "America/Antigua": "America / Antigua",
                "America/Aruba": "America / Aruba",
                "America/Barbados": "America / Barbados",
                "America/Blanc-Sablon": "America / Blanc-Sablon",
                "America/Boa_Vista": "America / Boa-Vista",
                "America/Campo_Grande": "America / Campo-Grande",
                "America/Caracas": "America / Caracas",
                "America/Cuiaba": "America / Cuiaba",
                "America/Curacao": "America / Curacao",
                "America/Detroit": "America / Detroit",
                "America/Dominica": "America / Dominica",
                "America/Grand_Turk": "America / Grand-Turk",
                "America/Grenada": "America / Grenada",
                "America/Guadeloupe": "America / Guadeloupe",
                "America/Guyana": "America / Guyana",
                "America/Havana": "America / Havana",
                "America/Indiana/Indianapolis": "America / Indiana / Indianapolis",
                "America/Indiana/Marengo": "America / Indiana / Marengo",
                "America/Indiana/Petersburg": "America / Indiana / Petersburg",
                "America/Indiana/Vevay": "America / Indiana / Vevay",
                "America/Indiana/Vincennes": "America / Indiana / Vincennes",
                "America/Indiana/Winamac": "America / Indiana / Winamac",
                "America/Iqaluit": "America / Iqaluit",
                "America/Kentucky/Louisville": "America / Kentucky / Louisville",
                "America/Kentucky/Monticello": "America / Kentucky / Monticello",
                "America/Kralendijk": "America / Kralendijk",
                "America/La_Paz": "America / La-Paz",
                "America/Lower_Princes": "America / Lower-Princes",
                "America/Manaus": "America / Manaus",
                "America/Marigot": "America / Marigot",
                "America/Martinique": "America / Martinique",
                "America/Montserrat": "America / Montserrat",
                "America/Nassau": "America / Nassau",
                "America/New_York": "America / New-York",
                "America/Port-au-Prince": "America / Port-au-Prince",
                "America/Port_of_Spain": "America / Port-of-Spain",
                "America/Porto_Velho": "America / Porto-Velho",
                "America/Puerto_Rico": "America / Puerto-Rico",
                "America/Santiago": "America / Santiago",
                "America/Santo_Domingo": "America / Santo-Domingo",
                "America/St_Barthelemy": "America / St-Barthelemy",
                "America/St_Kitts": "America / St-Kitts",
                "America/St_Lucia": "America / St-Lucia",
                "America/St_Thomas": "America / St-Thomas",
                "America/St_Vincent": "America / St-Vincent",
                "America/Toronto": "America / Toronto",
                "America/Tortola": "America / Tortola",
            ]),
        -18000: (
            formattedOffset: "−05:00",
            items: [
                "America/Atikokan": "America / Atikokan",
                "America/Bogota": "America / Bogota",
                "America/Cancun": "America / Cancun",
                "America/Cayman": "America / Cayman",
                "America/Chicago": "America / Chicago",
                "America/Eirunepe": "America / Eirunepe",
                "America/Guayaquil": "America / Guayaquil",
                "America/Indiana/Knox": "America / Indiana / Knox",
                "America/Indiana/Tell_City": "America / Indiana / Tell-City",
                "America/Jamaica": "America / Jamaica",
                "America/Lima": "America / Lima",
                "America/Matamoros": "America / Matamoros",
                "America/Menominee": "America / Menominee",
                "America/North_Dakota/Beulah": "America / North-Dakota / Beulah",
                "America/North_Dakota/Center": "America / North-Dakota / Center",
                "America/North_Dakota/New_Salem": "America / North-Dakota / New-Salem",
                "America/Ojinaga": "America / Ojinaga",
                "America/Panama": "America / Panama",
                "America/Rankin_Inlet": "America / Rankin-Inlet",
                "America/Resolute": "America / Resolute",
                "America/Rio_Branco": "America / Rio-Branco",
                "America/Winnipeg": "America / Winnipeg",
            ]),
        -21600: (
            formattedOffset: "−06:00",
            items: [
                "America/Bahia_Banderas": "America / Bahia-Banderas",
                "America/Belize": "America / Belize",
                "America/Boise": "America / Boise",
                "America/Cambridge_Bay": "America / Cambridge-Bay",
                "America/Chihuahua": "America / Chihuahua",
                "America/Ciudad_Juarez": "America / Ciudad-Juarez",
                "America/Costa_Rica": "America / Costa-Rica",
                "America/Denver": "America / Denver",
                "America/Edmonton": "America / Edmonton",
                "America/El_Salvador": "America / El-Salvador",
                "America/Guatemala": "America / Guatemala",
                "America/Inuvik": "America / Inuvik",
                "America/Managua": "America / Managua",
                "America/Merida": "America / Merida",
                "America/Mexico_City": "America / Mexico-City",
                "America/Monterrey": "America / Monterrey",
                "America/Regina": "America / Regina",
                "America/Swift_Current": "America / Swift-Current",
                "America/Tegucigalpa": "America / Tegucigalpa",
                "Pacific/Easter": "Pacific / Easter",
                "Pacific/Galapagos": "Pacific / Galapagos",
            ]),
        -25200: (
            formattedOffset: "−07:00",
            items: [
                "America/Creston": "America / Creston",
                "America/Dawson": "America / Dawson",
                "America/Dawson_Creek": "America / Dawson-Creek",
                "America/Fort_Nelson": "America / Fort-Nelson",
                "America/Hermosillo": "America / Hermosillo",
                "America/Los_Angeles": "America / Los-Angeles",
                "America/Mazatlan": "America / Mazatlan",
                "America/Phoenix": "America / Phoenix",
                "America/Tijuana": "America / Tijuana",
                "America/Vancouver": "America / Vancouver",
                "America/Whitehorse": "America / Whitehorse",
            ]),
        -28800: (
            formattedOffset: "−08:00",
            items: [
                "America/Anchorage": "America / Anchorage",
                "America/Juneau": "America / Juneau",
                "America/Metlakatla": "America / Metlakatla",
                "America/Nome": "America / Nome",
                "America/Sitka": "America / Sitka",
                "America/Yakutat": "America / Yakutat",
                "Pacific/Pitcairn": "Pacific / Pitcairn",
            ]),
        -32400: (
            formattedOffset: "−09:00",
            items: [
                "America/Adak": "America / Adak",
                "Pacific/Gambier": "Pacific / Gambier",
            ]),
        -34200: (
            formattedOffset: "−09:30",
            items: [
                "Pacific/Marquesas": "Pacific / Marquesas",
            ]),
        -36000: (
            formattedOffset: "−10:00",
            items: [
                "Pacific/Honolulu": "Pacific / Honolulu",
                "Pacific/Rarotonga": "Pacific / Rarotonga",
                "Pacific/Tahiti": "Pacific / Tahiti",
            ]),
        -39600: (
            formattedOffset: "−11:00",
            items: [
                "Pacific/Midway": "Pacific / Midway",
                "Pacific/Niue": "Pacific / Niue",
                "Pacific/Pago_Pago": "Pacific / Pago-Pago",
            ]),
    ]

}
