
/* ############################################################# */
/* ### Copyright © 2026 Maxim Rysevets. All rights reserved. ### */
/* ############################################################# */

import Foundation

extension Date {

    enum Format: String {
        case iso8601         = "yyyy-MM-dd HH:mm:ss"
        case iso8601Timezone = "yyyy-MM-dd HH:mm:ss Z"
        case iso8601Mono     = "yyyyMMdd_HHmmss"
        case convenientDate  = "d MMM yyyy"
        case convenientTime  = "HH:mm:ss"
    }

    var formatConvenient: String {
        let formatter = DateFormatter()
        formatter.dateFormat = String(
            format: NSLocalizedString("%@ 'at' %@", comment: ""),
            Self.Format.convenientDate.rawValue,
            Self.Format.convenientTime.rawValue )
        return formatter.string(from: self)
    }

    var formatISO8601withTZ: String {
        let formatter = DateFormatter()
        formatter.dateFormat = Self.Format.iso8601Timezone.rawValue
        formatter.locale = Locale(identifier: "en_US_POSIX")
        return formatter.string(from: self)
    }

    var formatISO8601: String {
        let formatter = DateFormatter()
        formatter.dateFormat = Self.Format.iso8601Timezone.rawValue
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.timeZone = TimeZone(secondsFromGMT: 0)
        return formatter.string(from: self)
    }

    var formatISO8601Mono: String {
        let formatter = DateFormatter()
        formatter.dateFormat = Self.Format.iso8601Mono.rawValue
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.timeZone = TimeZone(secondsFromGMT: 0)
        let mSec = Int(Self().timeIntervalSince1970.fractionalPart * 1_000)
        return formatter.string(from: self) + "-\(mSec)"
    }

    var day   : Int { get { Calendar.current.component(.day   , from: self) } set { self._updateComponent(day   : newValue) } }
    var month : Int { get { Calendar.current.component(.month , from: self) } set { self._updateComponent(month : newValue) } }
    var year  : Int { get { Calendar.current.component(.year  , from: self) } set { self._updateComponent(year  : newValue) } }
    var hour  : Int { get { Calendar.current.component(.hour  , from: self) } set { self._updateComponent(hour  : newValue) } }
    var minute: Int { get { Calendar.current.component(.minute, from: self) } set { self._updateComponent(minute: newValue) } }
    var second: Int { get { Calendar.current.component(.second, from: self) } set { self._updateComponent(second: newValue) } }

    private mutating func _updateComponent(
        day   : Int? = nil,
        month : Int? = nil,
        year  : Int? = nil,
        hour  : Int? = nil,
        minute: Int? = nil,
        second: Int? = nil,
    ) {
        var components = Calendar.current.dateComponents([
            .day, .month, .year, .hour, .minute, .second
        ], from: self)

        if let day    { components.day    = day }
        if let month  { components.month  = month }
        if let year   { components.year   = year }
        if let hour   { components.hour   = hour }
        if let minute { components.minute = minute }
        if let second { components.second = second }

        if let newDate = Calendar.current.date(from: components) {
            self = newDate
        }
    }

    static public let MONTH_NAMES = [
         1: "January",
         2: "February",
         3: "March",
         4: "April",
         5: "May",
         6: "June",
         7: "July",
         8: "August",
         9: "September",
        10: "October",
        11: "November",
        12: "December",
    ]

    static public let TIME_ZONES_OFFSSET: [String: Int] = [
        "Africa/Abidjan": 0,
        "Africa/Accra": 0,
        "Africa/Addis_Ababa": 10800,
        "Africa/Algiers": 3600,
        "Africa/Asmara": 10800,
        "Africa/Bamako": 0,
        "Africa/Bangui": 3600,
        "Africa/Banjul": 0,
        "Africa/Bissau": 0,
        "Africa/Blantyre": 7200,
        "Africa/Brazzaville": 3600,
        "Africa/Bujumbura": 7200,
        "Africa/Cairo": 10800,
        "Africa/Casablanca": 3600,
        "Africa/Ceuta": 7200,
        "Africa/Conakry": 0,
        "Africa/Dakar": 0,
        "Africa/Dar_es_Salaam": 10800,
        "Africa/Djibouti": 10800,
        "Africa/Douala": 3600,
        "Africa/El_Aaiun": 3600,
        "Africa/Freetown": 0,
        "Africa/Gaborone": 7200,
        "Africa/Harare": 7200,
        "Africa/Johannesburg": 7200,
        "Africa/Juba": 7200,
        "Africa/Kampala": 10800,
        "Africa/Khartoum": 7200,
        "Africa/Kigali": 7200,
        "Africa/Kinshasa": 3600,
        "Africa/Lagos": 3600,
        "Africa/Libreville": 3600,
        "Africa/Lome": 0,
        "Africa/Luanda": 3600,
        "Africa/Lubumbashi": 7200,
        "Africa/Lusaka": 7200,
        "Africa/Malabo": 3600,
        "Africa/Maputo": 7200,
        "Africa/Maseru": 7200,
        "Africa/Mbabane": 7200,
        "Africa/Mogadishu": 10800,
        "Africa/Monrovia": 0,
        "Africa/Nairobi": 10800,
        "Africa/Ndjamena": 3600,
        "Africa/Niamey": 3600,
        "Africa/Nouakchott": 0,
        "Africa/Ouagadougou": 0,
        "Africa/Porto-Novo": 3600,
        "Africa/Sao_Tome": 0,
        "Africa/Tripoli": 7200,
        "Africa/Tunis": 3600,
        "Africa/Windhoek": 7200,
        "America/Adak": -32400,
        "America/Anchorage": -28800,
        "America/Anguilla": -14400,
        "America/Antigua": -14400,
        "America/Araguaina": -10800,
        "America/Argentina/Buenos_Aires": -10800,
        "America/Argentina/Catamarca": -10800,
        "America/Argentina/Cordoba": -10800,
        "America/Argentina/Jujuy": -10800,
        "America/Argentina/La_Rioja": -10800,
        "America/Argentina/Mendoza": -10800,
        "America/Argentina/Rio_Gallegos": -10800,
        "America/Argentina/Salta": -10800,
        "America/Argentina/San_Juan": -10800,
        "America/Argentina/San_Luis": -10800,
        "America/Argentina/Tucuman": -10800,
        "America/Argentina/Ushuaia": -10800,
        "America/Aruba": -14400,
        "America/Asuncion": -10800,
        "America/Atikokan": -18000,
        "America/Bahia_Banderas": -21600,
        "America/Bahia": -10800,
        "America/Barbados": -14400,
        "America/Belem": -10800,
        "America/Belize": -21600,
        "America/Blanc-Sablon": -14400,
        "America/Boa_Vista": -14400,
        "America/Bogota": -18000,
        "America/Boise": -21600,
        "America/Cambridge_Bay": -21600,
        "America/Campo_Grande": -14400,
        "America/Cancun": -18000,
        "America/Caracas": -14400,
        "America/Cayenne": -10800,
        "America/Cayman": -18000,
        "America/Chicago": -18000,
        "America/Chihuahua": -21600,
        "America/Ciudad_Juarez": -21600,
        "America/Costa_Rica": -21600,
        "America/Coyhaique": -10800,
        "America/Creston": -25200,
        "America/Cuiaba": -14400,
        "America/Curacao": -14400,
        "America/Danmarkshavn": 0,
        "America/Dawson_Creek": -25200,
        "America/Dawson": -25200,
        "America/Denver": -21600,
        "America/Detroit": -14400,
        "America/Dominica": -14400,
        "America/Edmonton": -21600,
        "America/Eirunepe": -18000,
        "America/El_Salvador": -21600,
        "America/Fort_Nelson": -25200,
        "America/Fortaleza": -10800,
        "America/Glace_Bay": -10800,
        "America/Goose_Bay": -10800,
        "America/Grand_Turk": -14400,
        "America/Grenada": -14400,
        "America/Guadeloupe": -14400,
        "America/Guatemala": -21600,
        "America/Guayaquil": -18000,
        "America/Guyana": -14400,
        "America/Halifax": -10800,
        "America/Havana": -14400,
        "America/Hermosillo": -25200,
        "America/Indiana/Indianapolis": -14400,
        "America/Indiana/Knox": -18000,
        "America/Indiana/Marengo": -14400,
        "America/Indiana/Petersburg": -14400,
        "America/Indiana/Tell_City": -18000,
        "America/Indiana/Vevay": -14400,
        "America/Indiana/Vincennes": -14400,
        "America/Indiana/Winamac": -14400,
        "America/Inuvik": -21600,
        "America/Iqaluit": -14400,
        "America/Jamaica": -18000,
        "America/Juneau": -28800,
        "America/Kentucky/Louisville": -14400,
        "America/Kentucky/Monticello": -14400,
        "America/Kralendijk": -14400,
        "America/La_Paz": -14400,
        "America/Lima": -18000,
        "America/Los_Angeles": -25200,
        "America/Lower_Princes": -14400,
        "America/Maceio": -10800,
        "America/Managua": -21600,
        "America/Manaus": -14400,
        "America/Marigot": -14400,
        "America/Martinique": -14400,
        "America/Matamoros": -18000,
        "America/Mazatlan": -25200,
        "America/Menominee": -18000,
        "America/Merida": -21600,
        "America/Metlakatla": -28800,
        "America/Mexico_City": -21600,
        "America/Miquelon": -7200,
        "America/Moncton": -10800,
        "America/Monterrey": -21600,
        "America/Montevideo": -10800,
        "America/Montserrat": -14400,
        "America/Nassau": -14400,
        "America/New_York": -14400,
        "America/Nome": -28800,
        "America/Noronha": -7200,
        "America/North_Dakota/Beulah": -18000,
        "America/North_Dakota/Center": -18000,
        "America/North_Dakota/New_Salem": -18000,
        "America/Nuuk": -3600,
        "America/Ojinaga": -18000,
        "America/Panama": -18000,
        "America/Paramaribo": -10800,
        "America/Phoenix": -25200,
        "America/Port_of_Spain": -14400,
        "America/Port-au-Prince": -14400,
        "America/Porto_Velho": -14400,
        "America/Puerto_Rico": -14400,
        "America/Punta_Arenas": -10800,
        "America/Rankin_Inlet": -18000,
        "America/Recife": -10800,
        "America/Regina": -21600,
        "America/Resolute": -18000,
        "America/Rio_Branco": -18000,
        "America/Santarem": -10800,
        "America/Santiago": -14400,
        "America/Santo_Domingo": -14400,
        "America/Sao_Paulo": -10800,
        "America/Scoresbysund": -3600,
        "America/Sitka": -28800,
        "America/St_Barthelemy": -14400,
        "America/St_Johns": -9000,
        "America/St_Kitts": -14400,
        "America/St_Lucia": -14400,
        "America/St_Thomas": -14400,
        "America/St_Vincent": -14400,
        "America/Swift_Current": -21600,
        "America/Tegucigalpa": -21600,
        "America/Thule": -10800,
        "America/Tijuana": -25200,
        "America/Toronto": -14400,
        "America/Tortola": -14400,
        "America/Vancouver": -25200,
        "America/Whitehorse": -25200,
        "America/Winnipeg": -18000,
        "America/Yakutat": -28800,
        "Antarctica/Casey": 28800,
        "Antarctica/Davis": 25200,
        "Antarctica/DumontDUrville": 36000,
        "Antarctica/Macquarie": 36000,
        "Antarctica/Mawson": 18000,
        "Antarctica/McMurdo": 43200,
        "Antarctica/Palmer": -10800,
        "Antarctica/Rothera": -10800,
        "Antarctica/Syowa": 10800,
        "Antarctica/Troll": 7200,
        "Antarctica/Vostok": 18000,
        "Arctic/Longyearbyen": 7200,
        "Asia/Aden": 10800,
        "Asia/Almaty": 18000,
        "Asia/Amman": 10800,
        "Asia/Anadyr": 43200,
        "Asia/Aqtau": 18000,
        "Asia/Aqtobe": 18000,
        "Asia/Ashgabat": 18000,
        "Asia/Atyrau": 18000,
        "Asia/Baghdad": 10800,
        "Asia/Bahrain": 10800,
        "Asia/Baku": 14400,
        "Asia/Bangkok": 25200,
        "Asia/Barnaul": 25200,
        "Asia/Beirut": 10800,
        "Asia/Bishkek": 21600,
        "Asia/Brunei": 28800,
        "Asia/Chita": 32400,
        "Asia/Colombo": 19800,
        "Asia/Damascus": 10800,
        "Asia/Dhaka": 21600,
        "Asia/Dili": 32400,
        "Asia/Dubai": 14400,
        "Asia/Dushanbe": 18000,
        "Asia/Famagusta": 10800,
        "Asia/Gaza": 10800,
        "Asia/Hebron": 10800,
        "Asia/Ho_Chi_Minh": 25200,
        "Asia/Hong_Kong": 28800,
        "Asia/Hovd": 25200,
        "Asia/Irkutsk": 28800,
        "Asia/Jakarta": 25200,
        "Asia/Jayapura": 32400,
        "Asia/Jerusalem": 10800,
        "Asia/Kabul": 16200,
        "Asia/Kamchatka": 43200,
        "Asia/Karachi": 18000,
        "Asia/Kathmandu": 20700,
        "Asia/Khandyga": 32400,
        "Asia/Kolkata": 19800,
        "Asia/Krasnoyarsk": 25200,
        "Asia/Kuala_Lumpur": 28800,
        "Asia/Kuching": 28800,
        "Asia/Kuwait": 10800,
        "Asia/Macau": 28800,
        "Asia/Magadan": 39600,
        "Asia/Makassar": 28800,
        "Asia/Manila": 28800,
        "Asia/Muscat": 14400,
        "Asia/Nicosia": 10800,
        "Asia/Novokuznetsk": 25200,
        "Asia/Novosibirsk": 25200,
        "Asia/Omsk": 21600,
        "Asia/Oral": 18000,
        "Asia/Phnom_Penh": 25200,
        "Asia/Pontianak": 25200,
        "Asia/Pyongyang": 32400,
        "Asia/Qatar": 10800,
        "Asia/Qostanay": 18000,
        "Asia/Qyzylorda": 18000,
        "Asia/Riyadh": 10800,
        "Asia/Sakhalin": 39600,
        "Asia/Samarkand": 18000,
        "Asia/Seoul": 32400,
        "Asia/Shanghai": 28800,
        "Asia/Singapore": 28800,
        "Asia/Srednekolymsk": 39600,
        "Asia/Taipei": 28800,
        "Asia/Tashkent": 18000,
        "Asia/Tbilisi": 14400,
        "Asia/Tehran": 12600,
        "Asia/Thimphu": 21600,
        "Asia/Tokyo": 32400,
        "Asia/Tomsk": 25200,
        "Asia/Ulaanbaatar": 28800,
        "Asia/Urumqi": 21600,
        "Asia/Ust-Nera": 36000,
        "Asia/Vientiane": 25200,
        "Asia/Vladivostok": 36000,
        "Asia/Yakutsk": 32400,
        "Asia/Yangon": 23400,
        "Asia/Yekaterinburg": 18000,
        "Asia/Yerevan": 14400,
        "Atlantic/Azores": 0,
        "Atlantic/Bermuda": -10800,
        "Atlantic/Canary": 3600,
        "Atlantic/Cape_Verde": -3600,
        "Atlantic/Faroe": 3600,
        "Atlantic/Madeira": 3600,
        "Atlantic/Reykjavik": 0,
        "Atlantic/South_Georgia": -7200,
        "Atlantic/St_Helena": 0,
        "Atlantic/Stanley": -10800,
        "Australia/Adelaide": 34200,
        "Australia/Brisbane": 36000,
        "Australia/Broken_Hill": 34200,
        "Australia/Darwin": 34200,
        "Australia/Eucla": 31500,
        "Australia/Hobart": 36000,
        "Australia/Lindeman": 36000,
        "Australia/Lord_Howe": 37800,
        "Australia/Melbourne": 36000,
        "Australia/Perth": 28800,
        "Australia/Sydney": 36000,
        "Europe/Amsterdam": 7200,
        "Europe/Andorra": 7200,
        "Europe/Astrakhan": 14400,
        "Europe/Athens": 10800,
        "Europe/Belgrade": 7200,
        "Europe/Berlin": 7200,
        "Europe/Bratislava": 7200,
        "Europe/Brussels": 7200,
        "Europe/Bucharest": 10800,
        "Europe/Budapest": 7200,
        "Europe/Busingen": 7200,
        "Europe/Chisinau": 10800,
        "Europe/Copenhagen": 7200,
        "Europe/Dublin": 3600,
        "Europe/Gibraltar": 7200,
        "Europe/Guernsey": 3600,
        "Europe/Helsinki": 10800,
        "Europe/Isle_of_Man": 3600,
        "Europe/Istanbul": 10800,
        "Europe/Jersey": 3600,
        "Europe/Kaliningrad": 7200,
        "Europe/Kirov": 10800,
        "Europe/Kyiv": 10800,
        "Europe/Lisbon": 3600,
        "Europe/Ljubljana": 7200,
        "Europe/London": 3600,
        "Europe/Luxembourg": 7200,
        "Europe/Madrid": 7200,
        "Europe/Malta": 7200,
        "Europe/Mariehamn": 10800,
        "Europe/Minsk": 10800,
        "Europe/Monaco": 7200,
        "Europe/Moscow": 10800,
        "Europe/Oslo": 7200,
        "Europe/Paris": 7200,
        "Europe/Podgorica": 7200,
        "Europe/Prague": 7200,
        "Europe/Riga": 10800,
        "Europe/Rome": 7200,
        "Europe/Samara": 14400,
        "Europe/San_Marino": 7200,
        "Europe/Sarajevo": 7200,
        "Europe/Saratov": 14400,
        "Europe/Simferopol": 10800,
        "Europe/Skopje": 7200,
        "Europe/Sofia": 10800,
        "Europe/Stockholm": 7200,
        "Europe/Tallinn": 10800,
        "Europe/Tirane": 7200,
        "Europe/Ulyanovsk": 14400,
        "Europe/Vaduz": 7200,
        "Europe/Vatican": 7200,
        "Europe/Vienna": 7200,
        "Europe/Vilnius": 10800,
        "Europe/Volgograd": 10800,
        "Europe/Warsaw": 7200,
        "Europe/Zagreb": 7200,
        "Europe/Zurich": 7200,
        "Indian/Antananarivo": 10800,
        "Indian/Chagos": 21600,
        "Indian/Christmas": 25200,
        "Indian/Cocos": 23400,
        "Indian/Comoro": 10800,
        "Indian/Kerguelen": 18000,
        "Indian/Mahe": 14400,
        "Indian/Maldives": 18000,
        "Indian/Mauritius": 14400,
        "Indian/Mayotte": 10800,
        "Indian/Reunion": 14400,
        "Pacific/Apia": 46800,
        "Pacific/Auckland": 43200,
        "Pacific/Bougainville": 39600,
        "Pacific/Chatham": 45900,
        "Pacific/Chuuk": 36000,
        "Pacific/Easter": -21600,
        "Pacific/Efate": 39600,
        "Pacific/Fakaofo": 46800,
        "Pacific/Fiji": 43200,
        "Pacific/Funafuti": 43200,
        "Pacific/Galapagos": -21600,
        "Pacific/Gambier": -32400,
        "Pacific/Guadalcanal": 39600,
        "Pacific/Guam": 36000,
        "Pacific/Honolulu": -36000,
        "Pacific/Kanton": 46800,
        "Pacific/Kiritimati": 50400,
        "Pacific/Kosrae": 39600,
        "Pacific/Kwajalein": 43200,
        "Pacific/Majuro": 43200,
        "Pacific/Marquesas": -34200,
        "Pacific/Midway": -39600,
        "Pacific/Nauru": 43200,
        "Pacific/Niue": -39600,
        "Pacific/Norfolk": 39600,
        "Pacific/Noumea": 39600,
        "Pacific/Pago_Pago": -39600,
        "Pacific/Palau": 32400,
        "Pacific/Pitcairn": -28800,
        "Pacific/Pohnpei": 39600,
        "Pacific/Port_Moresby": 36000,
        "Pacific/Rarotonga": -36000,
        "Pacific/Saipan": 36000,
        "Pacific/Tahiti": -36000,
        "Pacific/Tarawa": 43200,
        "Pacific/Tongatapu": 46800,
        "Pacific/Wake": 43200,
        "Pacific/Wallis": 43200,
        "UTC": 0,
    ]


    static public let TIME_ZONES_GROUPPED_LIST: [Int: (offsetFormatted: String, items: [String: String])] = [
        50400: (
            offsetFormatted: "+14:00",
            items: [
                "Pacific/Kiritimati": "Pacific / Kiritimati",
            ]),
        46800: (
            offsetFormatted: "+13:00",
            items: [
                "Pacific/Apia": "Pacific / Apia",
                "Pacific/Fakaofo": "Pacific / Fakaofo",
                "Pacific/Kanton": "Pacific / Kanton",
                "Pacific/Tongatapu": "Pacific / Tongatapu",
            ]),
        45900: (
            offsetFormatted: "+12:45",
            items: [
                "Pacific/Chatham": "Pacific / Chatham",
            ]),
        43200: (
            offsetFormatted: "+12:00",
            items: [
                "Antarctica/McMurdo": "Antarctica / McMurdo",
                "Asia/Anadyr": "Asia / Anadyr",
                "Asia/Kamchatka": "Asia / Kamchatka",
                "Pacific/Auckland": "Pacific / Auckland",
                "Pacific/Fiji": "Pacific / Fiji",
                "Pacific/Funafuti": "Pacific / Funafuti",
                "Pacific/Kwajalein": "Pacific / Kwajalein",
                "Pacific/Majuro": "Pacific / Majuro",
                "Pacific/Nauru": "Pacific / Nauru",
                "Pacific/Tarawa": "Pacific / Tarawa",
                "Pacific/Wake": "Pacific / Wake",
                "Pacific/Wallis": "Pacific / Wallis",
            ]),
        39600: (
            offsetFormatted: "+11:00",
            items: [
                "Asia/Magadan": "Asia / Magadan",
                "Asia/Sakhalin": "Asia / Sakhalin",
                "Asia/Srednekolymsk": "Asia / Srednekolymsk",
                "Pacific/Bougainville": "Pacific / Bougainville",
                "Pacific/Efate": "Pacific / Efate",
                "Pacific/Guadalcanal": "Pacific / Guadalcanal",
                "Pacific/Kosrae": "Pacific / Kosrae",
                "Pacific/Norfolk": "Pacific / Norfolk",
                "Pacific/Noumea": "Pacific / Noumea",
                "Pacific/Pohnpei": "Pacific / Pohnpei",
            ]),
        37800: (
            offsetFormatted: "+10:30",
            items: [
                "Australia/Lord_Howe": "Australia / Lord-Howe",
            ]),
        36000: (
            offsetFormatted: "+10:00",
            items: [
                "Antarctica/DumontDUrville": "Antarctica / DumontDUrville",
                "Antarctica/Macquarie": "Antarctica / Macquarie",
                "Asia/Ust-Nera": "Asia / Ust-Nera",
                "Asia/Vladivostok": "Asia / Vladivostok",
                "Australia/Brisbane": "Australia / Brisbane",
                "Australia/Hobart": "Australia / Hobart",
                "Australia/Lindeman": "Australia / Lindeman",
                "Australia/Melbourne": "Australia / Melbourne",
                "Australia/Sydney": "Australia / Sydney",
                "Pacific/Chuuk": "Pacific / Chuuk",
                "Pacific/Guam": "Pacific / Guam",
                "Pacific/Port_Moresby": "Pacific / Port-Moresby",
                "Pacific/Saipan": "Pacific / Saipan",
            ]),
        34200: (
            offsetFormatted: "+09:30",
            items: [
                "Australia/Adelaide": "Australia / Adelaide",
                "Australia/Broken_Hill": "Australia / Broken-Hill",
                "Australia/Darwin": "Australia / Darwin",
            ]),
        32400: (
            offsetFormatted: "+09:00",
            items: [
                "Asia/Chita": "Asia / Chita",
                "Asia/Dili": "Asia / Dili",
                "Asia/Jayapura": "Asia / Jayapura",
                "Asia/Khandyga": "Asia / Khandyga",
                "Asia/Pyongyang": "Asia / Pyongyang",
                "Asia/Seoul": "Asia / Seoul",
                "Asia/Tokyo": "Asia / Tokyo",
                "Asia/Yakutsk": "Asia / Yakutsk",
                "Pacific/Palau": "Pacific / Palau",
            ]),
        31500: (
            offsetFormatted: "+08:45",
            items: [
                "Australia/Eucla": "Australia / Eucla",
            ]),
        28800: (
            offsetFormatted: "+08:00",
            items: [
                "Antarctica/Casey": "Antarctica / Casey",
                "Asia/Brunei": "Asia / Brunei",
                "Asia/Hong_Kong": "Asia / Hong-Kong",
                "Asia/Irkutsk": "Asia / Irkutsk",
                "Asia/Kuala_Lumpur": "Asia / Kuala-Lumpur",
                "Asia/Kuching": "Asia / Kuching",
                "Asia/Macau": "Asia / Macau",
                "Asia/Makassar": "Asia / Makassar",
                "Asia/Manila": "Asia / Manila",
                "Asia/Shanghai": "Asia / Shanghai",
                "Asia/Singapore": "Asia / Singapore",
                "Asia/Taipei": "Asia / Taipei",
                "Asia/Ulaanbaatar": "Asia / Ulaanbaatar",
                "Australia/Perth": "Australia / Perth",
            ]),
        25200: (
            offsetFormatted: "+07:00",
            items: [
                "Antarctica/Davis": "Antarctica / Davis",
                "Asia/Bangkok": "Asia / Bangkok",
                "Asia/Barnaul": "Asia / Barnaul",
                "Asia/Ho_Chi_Minh": "Asia / Ho-Chi-Minh",
                "Asia/Hovd": "Asia / Hovd",
                "Asia/Jakarta": "Asia / Jakarta",
                "Asia/Krasnoyarsk": "Asia / Krasnoyarsk",
                "Asia/Novokuznetsk": "Asia / Novokuznetsk",
                "Asia/Novosibirsk": "Asia / Novosibirsk",
                "Asia/Phnom_Penh": "Asia / Phnom-Penh",
                "Asia/Pontianak": "Asia / Pontianak",
                "Asia/Tomsk": "Asia / Tomsk",
                "Asia/Vientiane": "Asia / Vientiane",
                "Indian/Christmas": "Indian / Christmas",
            ]),
        23400: (
            offsetFormatted: "+06:30",
            items: [
                "Asia/Yangon": "Asia / Yangon",
                "Indian/Cocos": "Indian / Cocos",
            ]),
        21600: (
            offsetFormatted: "+06:00",
            items: [
                "Asia/Bishkek": "Asia / Bishkek",
                "Asia/Dhaka": "Asia / Dhaka",
                "Asia/Omsk": "Asia / Omsk",
                "Asia/Thimphu": "Asia / Thimphu",
                "Asia/Urumqi": "Asia / Urumqi",
                "Indian/Chagos": "Indian / Chagos",
            ]),
        20700: (
            offsetFormatted: "+05:45",
            items: [
                "Asia/Kathmandu": "Asia / Kathmandu",
            ]),
        19800: (
            offsetFormatted: "+05:30",
            items: [
                "Asia/Colombo": "Asia / Colombo",
                "Asia/Kolkata": "Asia / Kolkata",
            ]),
        18000: (
            offsetFormatted: "+05:00",
            items: [
                "Antarctica/Mawson": "Antarctica / Mawson",
                "Antarctica/Vostok": "Antarctica / Vostok",
                "Asia/Almaty": "Asia / Almaty",
                "Asia/Aqtau": "Asia / Aqtau",
                "Asia/Aqtobe": "Asia / Aqtobe",
                "Asia/Ashgabat": "Asia / Ashgabat",
                "Asia/Atyrau": "Asia / Atyrau",
                "Asia/Dushanbe": "Asia / Dushanbe",
                "Asia/Karachi": "Asia / Karachi",
                "Asia/Oral": "Asia / Oral",
                "Asia/Qostanay": "Asia / Qostanay",
                "Asia/Qyzylorda": "Asia / Qyzylorda",
                "Asia/Samarkand": "Asia / Samarkand",
                "Asia/Tashkent": "Asia / Tashkent",
                "Asia/Yekaterinburg": "Asia / Yekaterinburg",
                "Indian/Kerguelen": "Indian / Kerguelen",
                "Indian/Maldives": "Indian / Maldives",
            ]),
        16200: (
            offsetFormatted: "+04:30",
            items: [
                "Asia/Kabul": "Asia / Kabul",
            ]),
        14400: (
            offsetFormatted: "+04:00",
            items: [
                "Asia/Baku": "Asia / Baku",
                "Asia/Dubai": "Asia / Dubai",
                "Asia/Muscat": "Asia / Muscat",
                "Asia/Tbilisi": "Asia / Tbilisi",
                "Asia/Yerevan": "Asia / Yerevan",
                "Europe/Astrakhan": "Europe / Astrakhan",
                "Europe/Samara": "Europe / Samara",
                "Europe/Saratov": "Europe / Saratov",
                "Europe/Ulyanovsk": "Europe / Ulyanovsk",
                "Indian/Mahe": "Indian / Mahe",
                "Indian/Mauritius": "Indian / Mauritius",
                "Indian/Reunion": "Indian / Reunion",
            ]),
        12600: (
            offsetFormatted: "+03:30",
            items: [
                "Asia/Tehran": "Asia / Tehran",
            ]),
        10800: (
            offsetFormatted: "+03:00",
            items: [
                "Africa/Addis_Ababa": "Africa / Addis-Ababa",
                "Africa/Asmara": "Africa / Asmara",
                "Africa/Cairo": "Africa / Cairo",
                "Africa/Dar_es_Salaam": "Africa / Dar-es-Salaam",
                "Africa/Djibouti": "Africa / Djibouti",
                "Africa/Kampala": "Africa / Kampala",
                "Africa/Mogadishu": "Africa / Mogadishu",
                "Africa/Nairobi": "Africa / Nairobi",
                "Antarctica/Syowa": "Antarctica / Syowa",
                "Asia/Aden": "Asia / Aden",
                "Asia/Amman": "Asia / Amman",
                "Asia/Baghdad": "Asia / Baghdad",
                "Asia/Bahrain": "Asia / Bahrain",
                "Asia/Beirut": "Asia / Beirut",
                "Asia/Damascus": "Asia / Damascus",
                "Asia/Famagusta": "Asia / Famagusta",
                "Asia/Gaza": "Asia / Gaza",
                "Asia/Hebron": "Asia / Hebron",
                "Asia/Jerusalem": "Asia / Jerusalem",
                "Asia/Kuwait": "Asia / Kuwait",
                "Asia/Nicosia": "Asia / Nicosia",
                "Asia/Qatar": "Asia / Qatar",
                "Asia/Riyadh": "Asia / Riyadh",
                "Europe/Athens": "Europe / Athens",
                "Europe/Bucharest": "Europe / Bucharest",
                "Europe/Chisinau": "Europe / Chisinau",
                "Europe/Helsinki": "Europe / Helsinki",
                "Europe/Istanbul": "Europe / Istanbul",
                "Europe/Kirov": "Europe / Kirov",
                "Europe/Kyiv": "Europe / Kyiv",
                "Europe/Mariehamn": "Europe / Mariehamn",
                "Europe/Minsk": "Europe / Minsk",
                "Europe/Moscow": "Europe / Moscow",
                "Europe/Riga": "Europe / Riga",
                "Europe/Simferopol": "Europe / Simferopol",
                "Europe/Sofia": "Europe / Sofia",
                "Europe/Tallinn": "Europe / Tallinn",
                "Europe/Vilnius": "Europe / Vilnius",
                "Europe/Volgograd": "Europe / Volgograd",
                "Indian/Antananarivo": "Indian / Antananarivo",
                "Indian/Comoro": "Indian / Comoro",
                "Indian/Mayotte": "Indian / Mayotte",
            ]),
        7200: (
            offsetFormatted: "+02:00",
            items: [
                "Africa/Blantyre": "Africa / Blantyre",
                "Africa/Bujumbura": "Africa / Bujumbura",
                "Africa/Ceuta": "Africa / Ceuta",
                "Africa/Gaborone": "Africa / Gaborone",
                "Africa/Harare": "Africa / Harare",
                "Africa/Johannesburg": "Africa / Johannesburg",
                "Africa/Juba": "Africa / Juba",
                "Africa/Khartoum": "Africa / Khartoum",
                "Africa/Kigali": "Africa / Kigali",
                "Africa/Lubumbashi": "Africa / Lubumbashi",
                "Africa/Lusaka": "Africa / Lusaka",
                "Africa/Maputo": "Africa / Maputo",
                "Africa/Maseru": "Africa / Maseru",
                "Africa/Mbabane": "Africa / Mbabane",
                "Africa/Tripoli": "Africa / Tripoli",
                "Africa/Windhoek": "Africa / Windhoek",
                "Antarctica/Troll": "Antarctica / Troll",
                "Arctic/Longyearbyen": "Arctic / Longyearbyen",
                "Europe/Amsterdam": "Europe / Amsterdam",
                "Europe/Andorra": "Europe / Andorra",
                "Europe/Belgrade": "Europe / Belgrade",
                "Europe/Berlin": "Europe / Berlin",
                "Europe/Bratislava": "Europe / Bratislava",
                "Europe/Brussels": "Europe / Brussels",
                "Europe/Budapest": "Europe / Budapest",
                "Europe/Busingen": "Europe / Busingen",
                "Europe/Copenhagen": "Europe / Copenhagen",
                "Europe/Gibraltar": "Europe / Gibraltar",
                "Europe/Kaliningrad": "Europe / Kaliningrad",
                "Europe/Ljubljana": "Europe / Ljubljana",
                "Europe/Luxembourg": "Europe / Luxembourg",
                "Europe/Madrid": "Europe / Madrid",
                "Europe/Malta": "Europe / Malta",
                "Europe/Monaco": "Europe / Monaco",
                "Europe/Oslo": "Europe / Oslo",
                "Europe/Paris": "Europe / Paris",
                "Europe/Podgorica": "Europe / Podgorica",
                "Europe/Prague": "Europe / Prague",
                "Europe/Rome": "Europe / Rome",
                "Europe/San_Marino": "Europe / San-Marino",
                "Europe/Sarajevo": "Europe / Sarajevo",
                "Europe/Skopje": "Europe / Skopje",
                "Europe/Stockholm": "Europe / Stockholm",
                "Europe/Tirane": "Europe / Tirane",
                "Europe/Vaduz": "Europe / Vaduz",
                "Europe/Vatican": "Europe / Vatican",
                "Europe/Vienna": "Europe / Vienna",
                "Europe/Warsaw": "Europe / Warsaw",
                "Europe/Zagreb": "Europe / Zagreb",
                "Europe/Zurich": "Europe / Zurich",
            ]),
        3600: (
            offsetFormatted: "+01:00",
            items: [
                "Africa/Algiers": "Africa / Algiers",
                "Africa/Bangui": "Africa / Bangui",
                "Africa/Brazzaville": "Africa / Brazzaville",
                "Africa/Casablanca": "Africa / Casablanca",
                "Africa/Douala": "Africa / Douala",
                "Africa/El_Aaiun": "Africa / El-Aaiun",
                "Africa/Kinshasa": "Africa / Kinshasa",
                "Africa/Lagos": "Africa / Lagos",
                "Africa/Libreville": "Africa / Libreville",
                "Africa/Luanda": "Africa / Luanda",
                "Africa/Malabo": "Africa / Malabo",
                "Africa/Ndjamena": "Africa / Ndjamena",
                "Africa/Niamey": "Africa / Niamey",
                "Africa/Porto-Novo": "Africa / Porto-Novo",
                "Africa/Tunis": "Africa / Tunis",
                "Atlantic/Canary": "Atlantic / Canary",
                "Atlantic/Faroe": "Atlantic / Faroe",
                "Atlantic/Madeira": "Atlantic / Madeira",
                "Europe/Dublin": "Europe / Dublin",
                "Europe/Guernsey": "Europe / Guernsey",
                "Europe/Isle_of_Man": "Europe / Isle-of-Man",
                "Europe/Jersey": "Europe / Jersey",
                "Europe/Lisbon": "Europe / Lisbon",
                "Europe/London": "Europe / London",
            ]),
        0: (
            offsetFormatted: "+00:00",
            items: [
                "Africa/Abidjan": "Africa / Abidjan",
                "Africa/Accra": "Africa / Accra",
                "Africa/Bamako": "Africa / Bamako",
                "Africa/Banjul": "Africa / Banjul",
                "Africa/Bissau": "Africa / Bissau",
                "Africa/Conakry": "Africa / Conakry",
                "Africa/Dakar": "Africa / Dakar",
                "Africa/Freetown": "Africa / Freetown",
                "Africa/Lome": "Africa / Lome",
                "Africa/Monrovia": "Africa / Monrovia",
                "Africa/Nouakchott": "Africa / Nouakchott",
                "Africa/Ouagadougou": "Africa / Ouagadougou",
                "Africa/Sao_Tome": "Africa / Sao-Tome",
                "America/Danmarkshavn": "America / Danmarkshavn",
                "Atlantic/Azores": "Atlantic / Azores",
                "Atlantic/Reykjavik": "Atlantic / Reykjavik",
                "Atlantic/St_Helena": "Atlantic / St-Helena",
                "UTC": "UTC",
            ]),
        -3600: (
            offsetFormatted: "−01:00",
            items: [
                "America/Nuuk": "America / Nuuk",
                "America/Scoresbysund": "America / Scoresbysund",
                "Atlantic/Cape_Verde": "Atlantic / Cape-Verde",
            ]),
        -7200: (
            offsetFormatted: "−02:00",
            items: [
                "America/Miquelon": "America / Miquelon",
                "America/Noronha": "America / Noronha",
                "Atlantic/South_Georgia": "Atlantic / South-Georgia",
            ]),
        -9000: (
            offsetFormatted: "−02:30",
            items: [
                "America/St_Johns": "America / St-Johns",
            ]),
        -10800: (
            offsetFormatted: "−03:00",
            items: [
                "America/Araguaina": "America / Araguaina",
                "America/Argentina/Buenos_Aires": "America / Argentina / Buenos-Aires",
                "America/Argentina/Catamarca": "America / Argentina / Catamarca",
                "America/Argentina/Cordoba": "America / Argentina / Cordoba",
                "America/Argentina/Jujuy": "America / Argentina / Jujuy",
                "America/Argentina/La_Rioja": "America / Argentina / La-Rioja",
                "America/Argentina/Mendoza": "America / Argentina / Mendoza",
                "America/Argentina/Rio_Gallegos": "America / Argentina / Rio-Gallegos",
                "America/Argentina/Salta": "America / Argentina / Salta",
                "America/Argentina/San_Juan": "America / Argentina / San-Juan",
                "America/Argentina/San_Luis": "America / Argentina / San-Luis",
                "America/Argentina/Tucuman": "America / Argentina / Tucuman",
                "America/Argentina/Ushuaia": "America / Argentina / Ushuaia",
                "America/Asuncion": "America / Asuncion",
                "America/Bahia": "America / Bahia",
                "America/Belem": "America / Belem",
                "America/Cayenne": "America / Cayenne",
                "America/Coyhaique": "America / Coyhaique",
                "America/Fortaleza": "America / Fortaleza",
                "America/Glace_Bay": "America / Glace-Bay",
                "America/Goose_Bay": "America / Goose-Bay",
                "America/Halifax": "America / Halifax",
                "America/Maceio": "America / Maceio",
                "America/Moncton": "America / Moncton",
                "America/Montevideo": "America / Montevideo",
                "America/Paramaribo": "America / Paramaribo",
                "America/Punta_Arenas": "America / Punta-Arenas",
                "America/Recife": "America / Recife",
                "America/Santarem": "America / Santarem",
                "America/Sao_Paulo": "America / Sao-Paulo",
                "America/Thule": "America / Thule",
                "Antarctica/Palmer": "Antarctica / Palmer",
                "Antarctica/Rothera": "Antarctica / Rothera",
                "Atlantic/Bermuda": "Atlantic / Bermuda",
                "Atlantic/Stanley": "Atlantic / Stanley",
            ]),
        -14400: (
            offsetFormatted: "−04:00",
            items: [
                "America/Anguilla": "America / Anguilla",
                "America/Antigua": "America / Antigua",
                "America/Aruba": "America / Aruba",
                "America/Barbados": "America / Barbados",
                "America/Blanc-Sablon": "America / Blanc-Sablon",
                "America/Boa_Vista": "America / Boa-Vista",
                "America/Campo_Grande": "America / Campo-Grande",
                "America/Caracas": "America / Caracas",
                "America/Cuiaba": "America / Cuiaba",
                "America/Curacao": "America / Curacao",
                "America/Detroit": "America / Detroit",
                "America/Dominica": "America / Dominica",
                "America/Grand_Turk": "America / Grand-Turk",
                "America/Grenada": "America / Grenada",
                "America/Guadeloupe": "America / Guadeloupe",
                "America/Guyana": "America / Guyana",
                "America/Havana": "America / Havana",
                "America/Indiana/Indianapolis": "America / Indiana / Indianapolis",
                "America/Indiana/Marengo": "America / Indiana / Marengo",
                "America/Indiana/Petersburg": "America / Indiana / Petersburg",
                "America/Indiana/Vevay": "America / Indiana / Vevay",
                "America/Indiana/Vincennes": "America / Indiana / Vincennes",
                "America/Indiana/Winamac": "America / Indiana / Winamac",
                "America/Iqaluit": "America / Iqaluit",
                "America/Kentucky/Louisville": "America / Kentucky / Louisville",
                "America/Kentucky/Monticello": "America / Kentucky / Monticello",
                "America/Kralendijk": "America / Kralendijk",
                "America/La_Paz": "America / La-Paz",
                "America/Lower_Princes": "America / Lower-Princes",
                "America/Manaus": "America / Manaus",
                "America/Marigot": "America / Marigot",
                "America/Martinique": "America / Martinique",
                "America/Montserrat": "America / Montserrat",
                "America/Nassau": "America / Nassau",
                "America/New_York": "America / New-York",
                "America/Port-au-Prince": "America / Port-au-Prince",
                "America/Port_of_Spain": "America / Port-of-Spain",
                "America/Porto_Velho": "America / Porto-Velho",
                "America/Puerto_Rico": "America / Puerto-Rico",
                "America/Santiago": "America / Santiago",
                "America/Santo_Domingo": "America / Santo-Domingo",
                "America/St_Barthelemy": "America / St-Barthelemy",
                "America/St_Kitts": "America / St-Kitts",
                "America/St_Lucia": "America / St-Lucia",
                "America/St_Thomas": "America / St-Thomas",
                "America/St_Vincent": "America / St-Vincent",
                "America/Toronto": "America / Toronto",
                "America/Tortola": "America / Tortola",
            ]),
        -18000: (
            offsetFormatted: "−05:00",
            items: [
                "America/Atikokan": "America / Atikokan",
                "America/Bogota": "America / Bogota",
                "America/Cancun": "America / Cancun",
                "America/Cayman": "America / Cayman",
                "America/Chicago": "America / Chicago",
                "America/Eirunepe": "America / Eirunepe",
                "America/Guayaquil": "America / Guayaquil",
                "America/Indiana/Knox": "America / Indiana / Knox",
                "America/Indiana/Tell_City": "America / Indiana / Tell-City",
                "America/Jamaica": "America / Jamaica",
                "America/Lima": "America / Lima",
                "America/Matamoros": "America / Matamoros",
                "America/Menominee": "America / Menominee",
                "America/North_Dakota/Beulah": "America / North-Dakota / Beulah",
                "America/North_Dakota/Center": "America / North-Dakota / Center",
                "America/North_Dakota/New_Salem": "America / North-Dakota / New-Salem",
                "America/Ojinaga": "America / Ojinaga",
                "America/Panama": "America / Panama",
                "America/Rankin_Inlet": "America / Rankin-Inlet",
                "America/Resolute": "America / Resolute",
                "America/Rio_Branco": "America / Rio-Branco",
                "America/Winnipeg": "America / Winnipeg",
            ]),
        -21600: (
            offsetFormatted: "−06:00",
            items: [
                "America/Bahia_Banderas": "America / Bahia-Banderas",
                "America/Belize": "America / Belize",
                "America/Boise": "America / Boise",
                "America/Cambridge_Bay": "America / Cambridge-Bay",
                "America/Chihuahua": "America / Chihuahua",
                "America/Ciudad_Juarez": "America / Ciudad-Juarez",
                "America/Costa_Rica": "America / Costa-Rica",
                "America/Denver": "America / Denver",
                "America/Edmonton": "America / Edmonton",
                "America/El_Salvador": "America / El-Salvador",
                "America/Guatemala": "America / Guatemala",
                "America/Inuvik": "America / Inuvik",
                "America/Managua": "America / Managua",
                "America/Merida": "America / Merida",
                "America/Mexico_City": "America / Mexico-City",
                "America/Monterrey": "America / Monterrey",
                "America/Regina": "America / Regina",
                "America/Swift_Current": "America / Swift-Current",
                "America/Tegucigalpa": "America / Tegucigalpa",
                "Pacific/Easter": "Pacific / Easter",
                "Pacific/Galapagos": "Pacific / Galapagos",
            ]),
        -25200: (
            offsetFormatted: "−07:00",
            items: [
                "America/Creston": "America / Creston",
                "America/Dawson": "America / Dawson",
                "America/Dawson_Creek": "America / Dawson-Creek",
                "America/Fort_Nelson": "America / Fort-Nelson",
                "America/Hermosillo": "America / Hermosillo",
                "America/Los_Angeles": "America / Los-Angeles",
                "America/Mazatlan": "America / Mazatlan",
                "America/Phoenix": "America / Phoenix",
                "America/Tijuana": "America / Tijuana",
                "America/Vancouver": "America / Vancouver",
                "America/Whitehorse": "America / Whitehorse",
            ]),
        -28800: (
            offsetFormatted: "−08:00",
            items: [
                "America/Anchorage": "America / Anchorage",
                "America/Juneau": "America / Juneau",
                "America/Metlakatla": "America / Metlakatla",
                "America/Nome": "America / Nome",
                "America/Sitka": "America / Sitka",
                "America/Yakutat": "America / Yakutat",
                "Pacific/Pitcairn": "Pacific / Pitcairn",
            ]),
        -32400: (
            offsetFormatted: "−09:00",
            items: [
                "America/Adak": "America / Adak",
                "Pacific/Gambier": "Pacific / Gambier",
            ]),
        -34200: (
            offsetFormatted: "−09:30",
            items: [
                "Pacific/Marquesas": "Pacific / Marquesas",
            ]),
        -36000: (
            offsetFormatted: "−10:00",
            items: [
                "Pacific/Honolulu": "Pacific / Honolulu",
                "Pacific/Rarotonga": "Pacific / Rarotonga",
                "Pacific/Tahiti": "Pacific / Tahiti",
            ]),
        -39600: (
            offsetFormatted: "−11:00",
            items: [
                "Pacific/Midway": "Pacific / Midway",
                "Pacific/Niue": "Pacific / Niue",
                "Pacific/Pago_Pago": "Pacific / Pago-Pago",
            ]),
    ]

}
